import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { SqlitePersistence } from "../platform/persistence/sqlite";
import { migrate, rollback } from "../platform/persistence/migrations";
import { PersistentJobRepository, PersistentProjectRepository } from "../platform/persistence/repositories";
import { DurableQueue } from "../platform/jobs/durableQueue";
import { FilesystemArtifactStore } from "../platform/artifacts/contentAddressedStore";
import { RetentionService } from "../platform/artifacts/retention";
import { validatePersistenceConfig } from "../platform/persistence/config";
import { PersistentSyncRuns } from "../platform/persistence/syncRuns";
import { backupArtifacts, verifyArtifactBackup } from "../platform/artifacts/backup";

const command = (projectId: string) => ({ schemaVersion: 1 as const, kind: "code" as const, codeProjectId: projectId, options: { fix: false } });

describe("E02 persistent projects, jobs and artifacts", () => {
  let root: string;
  let database: SqlitePersistence;
  beforeEach(async () => { root = await fs.mkdtemp(path.join(os.tmpdir(), "ai-auditor-e02-")); database = new SqlitePersistence(path.join(root, "local.db")); await migrate(database); for (const id of ["tenant-a", "tenant-b"]) await database.execute("INSERT INTO tenants(id,name,created_at) VALUES(?,?,?)", [id, id, new Date().toISOString()]); });
  afterEach(async () => { await database.close(); await fs.rm(root, { recursive: true, force: true }); });

  it("migrates forward and rolls back", async () => { const versions = await database.query<{ version: number }>("SELECT version FROM schema_migrations ORDER BY version"); expect(versions.map((row) => Number(row.version))).toEqual([1, 2]); await rollback(database, 1); expect((await database.query<{ version: number }>("SELECT version FROM schema_migrations")).map((row) => Number(row.version))).toEqual([1]); });

  it("isolates project queries by tenant and persists across restart", async () => { const projects = new PersistentProjectRepository(database); await projects.save("tenant-a", { schemaVersion: 1, kind: "code", id: "project-a" as never, name: "A" }, { repositoryPath: "C:/repo-a" }); expect(await projects.get("tenant-b", "project-a")).toBeUndefined(); await database.close(); database = new SqlitePersistence(path.join(root, "local.db")); await migrate(database); expect((await new PersistentProjectRepository(database).get("tenant-a", "project-a"))?.public.name).toBe("A"); });

  it("deduplicates submissions and event delivery by idempotency identity", async () => { const jobs = new PersistentJobRepository(database); const first = await jobs.create({ tenantId: "tenant-a", projectId: "p", idempotencyKey: "same", command: command("p") }); const duplicate = await jobs.create({ tenantId: "tenant-a", projectId: "p", idempotencyKey: "same", command: command("p") }); expect(duplicate.duplicate).toBe(true); expect(duplicate.job.id).toBe(first.job.id); const event = { schemaVersion: 1 as const, type: "job.started" as const, jobId: first.job.id, occurredAt: new Date().toISOString(), payload: {} }; await jobs.appendEvent(event); await jobs.appendEvent(event); expect((await jobs.events("tenant-a", first.job.id)).filter((row) => row.type === "job.started")).toHaveLength(1); expect(await jobs.get("tenant-b", first.job.id)).toBeUndefined(); });

  it("recovers an expired worker lease and preserves checkpoints/cancellation", async () => { const jobs = new PersistentJobRepository(database); const created = await jobs.create({ tenantId: "tenant-a", projectId: "p", idempotencyKey: "lease", command: command("p") }); const queue = new DurableQueue(database, "tenant-a"); const leased = await queue.lease("worker-1", 1); expect(leased?.id).toBe(created.job.id); await jobs.saveCheckpoint("tenant-a", created.job.id, { frontier: ["https://example.com/2"] }); await jobs.requestCancellation("tenant-a", created.job.id); await new Promise((resolve) => setTimeout(resolve, 5)); expect(await queue.recoverExpired()).toBe(1); const recovered = await jobs.get("tenant-a", created.job.id); expect(recovered?.status).toBe("queued"); expect(recovered?.checkpoint).toEqual({ frontier: ["https://example.com/2"] }); expect(recovered?.cancelRequestedAt).toBeDefined(); });

  it("stores content outside a repository, verifies checksum and honors retention/legal hold", async () => { const artifactRoot = path.join(root, "artifact-store"); const store = new FilesystemArtifactStore(artifactRoot, database, { tenantId: "tenant-a", projectId: "p", retainUntil: new Date(Date.now() - 1000).toISOString() }, 32); const ref = await store.put(Buffer.from("immutable-report"), "application/json"); expect(Buffer.from((await store.get(ref.id))!).toString()).toBe("immutable-report"); expect((await fs.readdir(artifactRoot, { recursive: true })).some((name) => String(name).endsWith(".partial"))).toBe(false); await database.execute("UPDATE artifacts SET legal_hold=1 WHERE id=?", [ref.id]); expect(await new RetentionService(database, artifactRoot).apply("tenant-a")).toEqual({ deleted: 0, held: 1 }); await database.execute("UPDATE artifacts SET legal_hold=0 WHERE id=?", [ref.id]); expect(await new RetentionService(database, artifactRoot).apply("tenant-a")).toEqual({ deleted: 1, held: 0 }); expect(await store.get(ref.id)).toBeUndefined(); });

  it("rejects partial/oversized artifacts", async () => { const store = new FilesystemArtifactStore(path.join(root, "artifacts"), database, { tenantId: "tenant-a", projectId: "p" }, 4); await expect(store.put(Buffer.from("12345"), "text/plain")).rejects.toThrow(/exceeds/); });

  it("keeps terminal jobs immutable and requires PostgreSQL plus S3 in team mode", async () => { const jobs = new PersistentJobRepository(database); const created = await jobs.create({ tenantId: "tenant-a", projectId: "p", idempotencyKey: "terminal", command: command("p") }); await jobs.markRunning("tenant-a", created.job.id); expect(await jobs.finish("tenant-a", created.job.id, "completed", { reportPath: "artifact://report" })).toBe(true); expect(await jobs.finish("tenant-a", created.job.id, "failed")).toBe(false); expect(() => validatePersistenceConfig({ mode: "team", databaseUrl: "sqlite://bad", s3Bucket: "" })).toThrow(/PostgreSQL/); expect(() => validatePersistenceConfig({ mode: "team", databaseUrl: "postgresql://db/team", s3Bucket: "" })).toThrow(/S3/); });

  it("processes auditable project deletion while preserving legal-hold artifacts", async () => { const projects = new PersistentProjectRepository(database); await projects.save("tenant-a", { schemaVersion: 1, kind: "code", id: "delete-me" as never, name: "Delete" }); const artifactRoot=path.join(root,"delete-artifacts"); const store=new FilesystemArtifactStore(artifactRoot,database,{tenantId:"tenant-a",projectId:"delete-me"}); const artifact=await store.put(Buffer.from("evidence"),"text/plain"); await database.execute("UPDATE artifacts SET legal_hold=1 WHERE id=?",[artifact.id]); const retention=new RetentionService(database,artifactRoot); const request=await retention.requestProjectDeletion("tenant-a","delete-me"); expect(await retention.processProjectDeletion("tenant-a",request)).toEqual({deleted:0,held:1}); expect(await projects.get("tenant-a","delete-me")).toBeUndefined(); expect(await store.get(artifact.id)).toBeDefined(); const outbox=await database.query<Record<string,unknown>>("SELECT * FROM outbox WHERE tenant_id=? AND aggregate_id=?",["tenant-a",request]); expect(outbox.map(row=>row.type)).toEqual(["project.deletion_requested","project.deleted"]); });
});

describe("E02 external sync idempotency", () => {
  it("deduplicates within a tenant while isolating another tenant", async () => { const root=await fs.mkdtemp(path.join(os.tmpdir(),"ai-auditor-sync-")); const database=new SqlitePersistence(path.join(root,"local.db")); try { await migrate(database); const syncs=new PersistentSyncRuns(database); const first=await syncs.create("tenant-a","search-console","sync-key",{cursor:"a"}); const duplicate=await syncs.create("tenant-a","search-console","sync-key",{cursor:"b"}); const other=await syncs.create("tenant-b","search-console","sync-key",{}); expect(duplicate).toEqual({id:first.id,duplicate:true}); expect(other.id).not.toBe(first.id); } finally { await database.close(); await fs.rm(root,{recursive:true,force:true}); } });
});

describe("E02 artifact backup",()=>{it("preserves and verifies checksums after backup",async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),"ai-auditor-backup-"));try{const source=path.join(root,"source"),destination=path.join(root,"backup");await fs.mkdir(path.join(source,"tenant","project"),{recursive:true});await fs.writeFile(path.join(source,"tenant","project","report.json"),"report");await backupArtifacts(source,destination);expect(await verifyArtifactBackup(destination)).toEqual({verified:1});await fs.writeFile(path.join(destination,"tenant","project","report.json"),"corrupt");await expect(verifyArtifactBackup(destination)).rejects.toThrow(/checksum/);}finally{await fs.rm(root,{recursive:true,force:true});}});});
