import { analyzeTechnicalSignals, isRobotsAllowed, parseRobotsTxt, validateSitemapXml } from "../seo/technicalSeo";
import { compareRenderStates, detectRenderingFramework } from "../seo/javascriptSeo";
import { validateStructuredData } from "../seo/structuredData";
import { ProjectConnectorRegistry, analyzeSearchPerformance, normalizeSearchMetric } from "../seo/searchData";
import { assessExperience, compareExperience, type ExperienceMetric } from "../seo/cwvLab";
import { createExperiment, evaluateExperiment } from "../seo/experiments";
import { createOrMergeAlert, previewNotification, transitionAlert } from "../seo/monitoring";
import { buildDigitalTwin, simulateTwinChange } from "../seo/digitalTwin";

describe("SEO Phase 3 technical engine", () => {
  it("parses precedence, wildcards, anchors and sitemap validation", () => { const robots=parseRobotsTxt("User-agent: *\nDisallow: /private/*\nAllow: /private/public$\nSitemap: https://x.test/s.xml"); expect(isRobotsAllowed("/private/a",robots)).toBe(false); expect(isRobotsAllowed("/private/public",robots)).toBe(true); expect(robots.sitemaps).toEqual(["https://x.test/s.xml"]); expect(validateSitemapXml("<urlset><url><loc>/relative</loc></url></urlset>","https://x.test/s.xml").findings[0].ruleId).toBe("sitemap-relative-url"); });
  it("finds header, soft-404, canonical and hreflang conflicts with evidence",()=>{const base={status:200,redirectChain:[],mimeType:"text/html",xRobotsTag:"",metaRobots:"",title:"ok",bodyText:"content",hreflang:[]};const findings=analyzeTechnicalSignals([{...base,url:"https://x/a",finalUrl:"https://x/a",canonical:"https://x/b",hreflang:[{language:"en",url:"https://x/b"}]},{...base,url:"https://x/b",finalUrl:"https://x/b",canonical:"https://x/a",title:"404 not found"}]);expect(findings.some(x=>x.ruleId==="canonical-loop")).toBe(true);expect(findings.some(x=>x.ruleId==="soft-404")).toBe(true);expect(findings.every(x=>x.evidence&&x.remediation)).toBe(true)});
});
describe("SEO Phase 4 JavaScript rendering",()=>{it("compares crawl-critical state and detects frameworks",()=>{const raw={state:"raw" as const,url:"/",title:"A",robots:"index",canonical:"/",hreflang:[],schemaTypes:[],text:"short",images:[],links:[]};const rendered={...raw,state:"rendered" as const,title:"B",text:"long ".repeat(100),links:["/a"]};const result=compareRenderStates([raw,rendered]);expect(result.clientOnlyContent).toBe(true);expect(result.differences.some(x=>x.field==="title")).toBe(true);expect(detectRenderingFramework(["vite.config.ts"],["vite"]).framework).toBe("Vite")})});
describe("SEO Phase 5 structured data",()=>{it("normalizes graphs and separates eligibility from guarantees",()=>{const html='<script type="application/ld+json">{"@context":"https://schema.org","@type":"Product","@id":"#p","name":"Invisible"}</script>';const result=validateStructuredData(html,"https://x.test/","Visible page",["Product"]);expect(result.entities[0].types).toContain("Product");expect(result.findings.some(x=>x.ruleId==="schema-required-property")).toBe(true);expect(result.richResultEligibility.guaranteed).toBe(false)})});
describe("SEO Phases 11-15 operations",()=>{it("normalizes read-only search evidence and detects decline",()=>{const old=normalizeSearchMetric("p","fixture",{date:"2026-01-01",page:"https://x/a",clicks:100,impressions:1000});const current=normalizeSearchMetric("p","fixture",{date:"2026-02-01",page:"https://x/a",clicks:50,impressions:1000});expect(analyzeSearchPerformance([current],[old]).some(x=>x.ruleId==="declining-page")).toBe(true);const registry=new ProjectConnectorRegistry();expect(()=>registry.connect("p","google-search-console",["search.write"])).toThrow(/read-only/);registry.connect("p","google-search-console",["search.read"]);registry.revoke("p","google-search-console");expect(registry.list("p")).toEqual([])});it("keeps lab/field separate and applies variance gates",()=>{const metric=(value:number,source:"lab"|"field"="lab"):ExperienceMetric=>({url:"/",metric:"LCP",value,source,device:"mobile",collectedAt:"2026-01-01"});expect(assessExperience([metric(2600),metric(2400,"field")]).violations).toHaveLength(1);expect(compareExperience([metric(1000)],[metric(1300)]).passed).toBe(false)});it("guards experiments and explains uncertainty",()=>{const exp=createExperiment({projectId:"p",campaignId:"c",type:"title",hypothesis:"Improve clarity",metric:"clicks",controlUrls:["/a"],testUrls:["/b"],rollout:.5,start:"2026-01-01",end:"2026-02-01",guardrails:{errors:1},rollbackConditions:[],annotations:[]});const result=evaluateExperiment(exp,{control:[10],test:[12]});expect(result.decision).toBe("inconclusive");expect(result.methodologicalLimits.length).toBeGreaterThan(0)});it("deduplicates alert state and previews without sending",()=>{const input={projectId:"p",ruleId:"noindex",severity:"high" as const,confidence:.9,urls:["/a"],evidence:{},recommendedAction:"Remove accidental noindex"};const alert=createOrMergeAlert(undefined,input,"2026-01-01");expect(createOrMergeAlert(alert,input,"2026-01-02").id).toBe(alert.id);expect(transitionAlert(alert,"acknowledged").state).toBe("acknowledged");expect(previewNotification(alert,"slack").send).toBe(false)});it("validates and simulates a versioned digital twin",()=>{const twin=buildDigitalTwin("p",[{id:"u",kind:"url",label:"/"},{id:"t",kind:"topic",label:"SEO"}],[{from:"u",to:"t",type:"covers"}],["crawl:1"]);const result=simulateTwinChange(twin,{removeNode:"u"});expect(result.blastRadius).toBe(1);expect(result.confidence).toBeGreaterThan(.4)})});
