import http from "node:http";
import { crawlSite, crawlToCsv, normalizeCrawlUrl } from "../analyzers/seoCrawler";

let server: http.Server; let origin: string;
beforeAll(async () => { server = http.createServer((req, res) => { const path = req.url ?? "/"; if (path === "/robots.txt") return res.end("User-agent: *\nDisallow: /blocked\nSitemap: /sitemap.xml"); if (path === "/sitemap.xml") return res.end(`<urlset><url><loc>${origin}/</loc></url><url><loc>${origin}/orphan</loc></url></urlset>`); if (path === "/broken") { res.statusCode = 404; return res.end("missing"); } if (path === "/blocked") return res.end("blocked"); const title = path === "/duplicate" ? "Home" : path.slice(1) || "Home"; res.setHeader("content-type", "text/html"); return res.end(`<html lang="en"><head><title>${title}</title><meta name="description" content="same description"><meta name="viewport" content="width=device-width"><link rel="canonical" href="${origin}${path}"></head><body><h1>${title}</h1><a href="/duplicate">duplicate</a><a href="/broken">broken</a><a href="/blocked">blocked</a></body></html>`); }); await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve)); origin = `http://127.0.0.1:${(server.address() as { port: number }).port}`; });
afterAll(() => new Promise<void>((resolve) => server.close(() => resolve())));

describe("controlled SEO crawler", () => {
  it("normalizes tracking parameters", () => expect(normalizeCrawlUrl("https://EXAMPLE.com/a/?utm_source=x&b=2#x")).toBe("https://example.com/a?b=2"));
  it("respects robots and detects site-wide issues within budgets", async () => { const result = await crawlSite(origin, { budget: { maxPages: 10, maxDepth: 3, concurrency: 2, delayMs: 0, maxDurationMs: 10_000, maxResponseBytes: 50_000 } }); expect(result.records.find((r) => r.url.endsWith("/blocked"))?.blockedByRobots).toBe(true); expect(result.issues.some((i) => i.ruleId === "duplicate-title")).toBe(true); expect(result.issues.some((i) => i.ruleId === "broken-url")).toBe(true); expect(crawlToCsv(result)).toContain('"url","status"'); });
  it("honors page and cancellation budgets", async () => { const limited = await crawlSite(origin, { budget: { maxPages: 1, maxDepth: 4, concurrency: 1, delayMs: 0, maxDurationMs: 10_000, maxResponseBytes: 50_000 } }); expect(limited.records).toHaveLength(1); expect(limited.status).toBe("budget-exhausted"); const controller = new AbortController(); controller.abort(); const cancelled = await crawlSite(origin, { signal: controller.signal }); expect(cancelled.status).toBe("cancelled"); });
});
