import fs from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import { glob } from "glob";

export interface ModuleNode { file: string; imports: string[]; exports: string[]; lines: number; incoming: number; outgoing: number; kind: "production" | "test" | "generated" }
export interface ArchitectureFinding { ruleId: string; severity: "low" | "medium" | "high"; message: string; files: string[]; confidence: "low" | "medium" | "high" }
export interface ArchitectureReport { nodes: ModuleNode[]; cycles: string[][]; findings: ArchitectureFinding[]; debtScore: number; debtFactors: Record<string, number> }

const extensions = [".ts", ".tsx", ".js", ".jsx", ".mts", ".cts", ".mjs", ".cjs"];
const posix = (value: string) => value.replace(/\\/g, "/");
async function resolveImport(root: string, from: string, specifier: string, files: Set<string>): Promise<string | undefined> { if (!specifier.startsWith(".")) return undefined; const base = path.resolve(root, path.dirname(from), specifier); for (const candidate of [base, ...extensions.map((ext) => base + ext), ...extensions.map((ext) => path.join(base, `index${ext}`))]) { const relative = posix(path.relative(root, candidate)); if (files.has(relative)) return relative; } return undefined; }

export async function analyzeArchitecture(root: string): Promise<ArchitectureReport> {
  const names = (await glob("**/*.{js,jsx,ts,tsx,mjs,cjs,mts,cts}", { cwd: root, nodir: true, ignore: ["**/node_modules/**", "**/dist/**", "**/build/**", "**/coverage/**", "ai-auditor-report/**"] })).map(posix).sort(); const fileSet = new Set(names); const nodes: ModuleNode[] = [];
  const externalImports = new Map<string, Set<string>>(); const packageRaw = await fs.readFile(path.join(root, "package.json"), "utf8").catch(() => "{}"); const pkg = JSON.parse(packageRaw) as { dependencies?: Record<string, string>; exports?: unknown; main?: string; module?: string };
  for (const file of names) { const source = await fs.readFile(path.join(root, file), "utf8"); const info = ts.preProcessFile(source, true, true); const imports: string[] = []; for (const imported of info.importedFiles) { const resolved = await resolveImport(root, file, imported.fileName, fileSet); if (resolved) imports.push(resolved); else if (!imported.fileName.startsWith(".")) { const packageName = imported.fileName.startsWith("@") ? imported.fileName.split("/").slice(0, 2).join("/") : imported.fileName.split("/")[0]; (externalImports.get(packageName) ?? externalImports.set(packageName, new Set()).get(packageName)!).add(file); } } const ast = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true); const exports = new Set<string>(); ast.forEachChild((node) => { const modifiers = ts.canHaveModifiers(node) ? ts.getModifiers(node) : undefined; if (modifiers?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)) { const named = (node as ts.NamedDeclaration).name; if (named && ts.isIdentifier(named)) exports.add(named.text); else exports.add("default"); } if (ts.isExportDeclaration(node) && node.exportClause && ts.isNamedExports(node.exportClause)) node.exportClause.elements.forEach((item) => exports.add(item.name.text)); }); nodes.push({ file, imports: [...new Set(imports)], exports: [...exports], lines: source.split(/\r?\n/).length, incoming: 0, outgoing: new Set(imports).size, kind: /(?:^|\/)(?:tests?|__tests__|fixtures?)\/|\.(?:test|spec)\./.test(file) ? "test" : /(?:^|\/)(?:generated|vendor)\//.test(file) ? "generated" : "production" }); }
  const byFile = new Map(nodes.map((node) => [node.file, node])); nodes.forEach((node) => node.imports.forEach((target) => { const found = byFile.get(target); if (found) found.incoming++; }));
  const cycles: string[][] = []; const visiting = new Set<string>(); const visited = new Set<string>(); const stack: string[] = []; const cycleKeys = new Set<string>(); const dfs = (file: string) => { if (visiting.has(file)) { const cycle = [...stack.slice(stack.indexOf(file)), file]; const key = [...new Set(cycle)].sort().join("|"); if (!cycleKeys.has(key)) { cycleKeys.add(key); cycles.push(cycle); } return; } if (visited.has(file)) return; visiting.add(file); stack.push(file); byFile.get(file)?.imports.forEach(dfs); stack.pop(); visiting.delete(file); visited.add(file); }; names.forEach(dfs);
  const findings: ArchitectureFinding[] = cycles.map((cycle) => ({ ruleId: "circular-dependency", severity: "high", message: `Circular dependency: ${cycle.join(" → ")}`, files: cycle, confidence: "high" })); const entries = new Set([pkg.main, pkg.module, "src/index.ts", "src/index.js", "src/main.ts", "src/main.tsx"].filter((v): v is string => typeof v === "string").map(posix));
  for (const node of nodes.filter((n) => n.kind === "production")) { if (node.lines > 500) findings.push({ ruleId: "oversized-module", severity: "medium", message: `${node.file} has ${node.lines} lines`, files: [node.file], confidence: "high" }); if (node.outgoing > 15 || node.incoming > 25) findings.push({ ruleId: "high-coupling", severity: "medium", message: `${node.file} has coupling ${node.incoming + node.outgoing}`, files: [node.file], confidence: "high" }); if (node.incoming === 0 && !entries.has(node.file) && !/(?:^|\/)(?:pages|routes|app)\//.test(node.file)) findings.push({ ruleId: "unused-file", severity: "low", message: `${node.file} has no known importers`, files: [node.file], confidence: "medium" }); }
  for (const dependency of Object.keys(pkg.dependencies ?? {})) if (!externalImports.has(dependency)) findings.push({ ruleId: "unused-dependency", severity: "low", message: `Direct dependency ${dependency} is not statically imported`, files: ["package.json"], confidence: "medium" });
  for (const node of nodes) { if (!node.exports.length || node.kind !== "production") continue; const importers = nodes.filter((other) => other.imports.includes(node.file)); if (!importers.length && !entries.has(node.file)) findings.push({ ruleId: "unused-exports", severity: "low", message: `${node.exports.length} export(s) in ${node.file} have no known consumers`, files: [node.file], confidence: "low" }); }
  const debtFactors = { cycles: cycles.length * 12, oversized: findings.filter((f) => f.ruleId === "oversized-module").length * 6, coupling: findings.filter((f) => f.ruleId === "high-coupling").length * 5, unused: findings.filter((f) => f.ruleId.startsWith("unused")).length * 2 }; const debtScore = Math.max(0, 100 - Object.values(debtFactors).reduce((a, b) => a + b, 0)); return { nodes, cycles, findings, debtScore, debtFactors };
}

export function architectureBlastRadius(report: ArchitectureReport, file: string): { direct: string[]; transitive: string[]; tests: string[]; score: number } { const reverse = new Map<string, string[]>(); report.nodes.forEach((node) => node.imports.forEach((target) => reverse.set(target, [...(reverse.get(target) ?? []), node.file]))); const direct = reverse.get(file) ?? []; const transitive = new Set<string>(); const queue = [...direct]; while (queue.length) { const next = queue.shift()!; if (transitive.has(next)) continue; transitive.add(next); queue.push(...(reverse.get(next) ?? [])); } const tests = [...transitive].filter((name) => report.nodes.find((node) => node.file === name)?.kind === "test"); return { direct, transitive: [...transitive], tests, score: Math.min(100, direct.length * 8 + transitive.size * 3) }; }
export function architectureToSarif(report: ArchitectureReport) { return { version: "2.1.0", runs: [{ tool: { driver: { name: "ai-auditor-architecture", rules: [...new Set(report.findings.map((f) => f.ruleId))].map((id) => ({ id })) } }, results: report.findings.map((finding) => ({ ruleId: finding.ruleId, level: finding.severity === "high" ? "error" : finding.severity === "medium" ? "warning" : "note", message: { text: finding.message }, locations: finding.files.map((file) => ({ physicalLocation: { artifactLocation: { uri: file } } })) })) }] }; }
