import fs from "node:fs/promises";
export interface RouteMetrics { route: string; profile: "mobile" | "desktop"; lcp: number; cls: number; tbt: number; speedIndex: number; performance: number }
export interface PerformanceBudget { route?: string; profile?: "mobile" | "desktop"; maxLcp?: number; maxCls?: number; maxTbt?: number; maxSpeedIndex?: number; minScore?: number; maxBundleBytes?: number }
export interface BundleModule { name: string; bytes: number; chunks: string[]; duplicated: boolean }
export interface BundleReport { tool: "vite" | "webpack" | "rollup" | "esbuild" | "unknown"; modules: BundleModule[]; totalBytes: number; duplicatedBytes: number }
export function metricsFromLighthouse(route: string, profile: "mobile" | "desktop", lhr: { categories?: Record<string, { score?: number | null }>; audits?: Record<string, { numericValue?: number }> }): RouteMetrics { const value = (id: string) => lhr.audits?.[id]?.numericValue ?? 0; return { route, profile, lcp: value("largest-contentful-paint"), cls: value("cumulative-layout-shift"), tbt: value("total-blocking-time"), speedIndex: value("speed-index"), performance: Math.round((lhr.categories?.performance?.score ?? 0) * 100) }; }
export async function parseBundleMetadata(file: string): Promise<BundleReport> { const raw = JSON.parse(await fs.readFile(file, "utf8")) as Record<string, unknown>; const modules = new Map<string, { bytes: number; chunks: string[] }>(); let tool: BundleReport["tool"] = "unknown"; if (raw.outputs && typeof raw.outputs === "object") { tool = "esbuild"; for (const [chunk, data] of Object.entries(raw.outputs as Record<string, { bytes?: number; inputs?: Record<string, { bytesInOutput?: number }> }>)) for (const [name, item] of Object.entries(data.inputs ?? {})) { const current = modules.get(name) ?? { bytes: 0, chunks: [] }; current.bytes += item.bytesInOutput ?? 0; current.chunks.push(chunk); modules.set(name, current); } } else if (Array.isArray(raw.chunks) || Array.isArray(raw.assets)) { tool = Array.isArray(raw.chunks) ? "rollup" : "webpack"; for (const chunk of (raw.chunks as Array<{ fileName?: string; modules?: Record<string, { renderedLength?: number }> }> ?? [])) for (const [name, item] of Object.entries(chunk.modules ?? {})) { const current = modules.get(name) ?? { bytes: 0, chunks: [] }; current.bytes += item.renderedLength ?? 0; current.chunks.push(chunk.fileName ?? "chunk"); modules.set(name, current); } for (const asset of (raw.assets as Array<{ name?: string; size?: number; chunks?: string[] }> ?? [])) modules.set(asset.name ?? "asset", { bytes: asset.size ?? 0, chunks: asset.chunks ?? [] }); } const result = [...modules].map(([name, value]) => ({ name, ...value, duplicated: value.chunks.length > 1 })); return { tool, modules: result.sort((a, b) => b.bytes - a.bytes), totalBytes: result.reduce((sum, item) => sum + item.bytes, 0), duplicatedBytes: result.filter((item) => item.duplicated).reduce((sum, item) => sum + item.bytes, 0) }; }
export function evaluatePerformanceBudgets(metrics: RouteMetrics[], bundle: BundleReport | undefined, budgets: PerformanceBudget[]) { const failures: string[] = []; for (const budget of budgets) for (const metric of metrics.filter((m) => (!budget.route || budget.route === m.route) && (!budget.profile || budget.profile === m.profile))) { if (budget.maxLcp !== undefined && metric.lcp > budget.maxLcp) failures.push(`${metric.route}/${metric.profile}: LCP ${metric.lcp} > ${budget.maxLcp}`); if (budget.maxCls !== undefined && metric.cls > budget.maxCls) failures.push(`${metric.route}/${metric.profile}: CLS ${metric.cls} > ${budget.maxCls}`); if (budget.maxTbt !== undefined && metric.tbt > budget.maxTbt) failures.push(`${metric.route}/${metric.profile}: TBT ${metric.tbt} > ${budget.maxTbt}`); if (budget.maxSpeedIndex !== undefined && metric.speedIndex > budget.maxSpeedIndex) failures.push(`${metric.route}/${metric.profile}: Speed Index ${metric.speedIndex} > ${budget.maxSpeedIndex}`); if (budget.minScore !== undefined && metric.performance < budget.minScore) failures.push(`${metric.route}/${metric.profile}: score ${metric.performance} < ${budget.minScore}`); } const maxBundle = Math.min(...budgets.map((b) => b.maxBundleBytes ?? Infinity)); if (bundle && bundle.totalBytes > maxBundle) failures.push(`Bundle ${bundle.totalBytes} bytes > ${maxBundle}`); return { passed: failures.length === 0, failures }; }
export function performanceScores(metrics: RouteMetrics[], bundle?: BundleReport) { const performance = metrics.length ? Math.round(metrics.reduce((sum, m) => sum + m.performance, 0) / metrics.length) : 0; const bundleScore = bundle ? Math.max(0, Math.round(100 - bundle.totalBytes / 50_000 - bundle.duplicatedBytes / 20_000)) : 0; return { performance, bundle: bundleScore }; }
