import { analyzeSeoHtml, type SeoFinding } from "./seoLab";
import { analyzeTechnicalSignals, isRobotsAllowed, parseRobotsTxt, validateSitemapXml, type TechnicalPageSignal } from "../seo/technicalSeo";
import { safeFetch } from "../platform/security/networkPolicy";
const crawlNetworkProfile = () => process.env.AI_AUDITOR_ALLOW_PRIVATE_NETWORK === "true" ? "private-network" as const : "public-web" as const;

async function guardedFetch(input: string, init: { signal?: AbortSignal } = {}) {
  const result = await safeFetch(input, { signal: init.signal, policy: { profile: crawlNetworkProfile() } });
  return { status: result.status, ok: result.ok, headers: new Headers(result.headers), url: result.url, redirectChain: result.redirectChain, text: async () => result.text(), arrayBuffer: async () => result.body.buffer.slice(result.body.byteOffset, result.body.byteOffset + result.body.byteLength) };
}
const fetch = guardedFetch;

export interface CrawlBudget { maxPages: number; maxDepth: number; concurrency: number; delayMs: number; maxDurationMs: number; maxResponseBytes: number }
export interface CrawlOptions { budget: CrawlBudget; include?: RegExp[]; exclude?: RegExp[]; includeSubdomains?: boolean; respectRobots?: boolean; signal?: AbortSignal; resume?: CrawlResult; onProgress?: (progress: CrawlProgress) => void }
export interface CrawlRecord { url: string; normalizedUrl: string; finalUrl?: string; status: number; depth: number; title: string; description: string; canonical: string; indexable: boolean; blockedByRobots: boolean; links: string[]; issueCount: number; bytes: number; mimeType?: string; xRobotsTag?: string; metaRobots?: string; redirectChain?: string[]; hreflang?: Array<{ language: string; url: string }>; bodyText?: string; error?: string }
export interface CrawlProgress { discovered: number; completed: number; queued: number; elapsedMs: number; current?: string }
export interface CrawlSiteIssue { ruleId: string; message: string; urls: string[]; severity: "low" | "medium" | "high" }
export interface CrawlResult { startedAt: string; completedAt: string; startUrl: string; status: "completed" | "cancelled" | "budget-exhausted"; records: CrawlRecord[]; issues: CrawlSiteIssue[]; sitemapUrls: string[]; progress: CrawlProgress }

export const DEFAULT_CRAWL_BUDGET: CrawlBudget = { maxPages: 100, maxDepth: 4, concurrency: 3, delayMs: 150, maxDurationMs: 120_000, maxResponseBytes: 2_000_000 };
export function normalizeCrawlUrl(input: string): string { const url = new URL(input); url.hash = ""; url.hostname = url.hostname.toLowerCase(); url.pathname = url.pathname.replace(/\/+/g, "/").replace(/\/$/, "") || "/"; [...url.searchParams.keys()].filter((key) => /^utm_|^(fbclid|gclid)$/i.test(key)).forEach((key) => url.searchParams.delete(key)); url.searchParams.sort(); return url.href; }
const extract = (html: string, pattern: RegExp) => pattern.exec(html)?.[1]?.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim() ?? "";
const escapeCsv = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
export function crawlToCsv(result: CrawlResult): string { return [["url", "status", "depth", "indexable", "canonical", "title", "description", "issues"].map(escapeCsv).join(","), ...result.records.map((r) => [r.url, r.status, r.depth, r.indexable, r.canonical, r.title, r.description, r.issueCount].map(escapeCsv).join(","))].join("\n"); }

function allowed(url: URL, root: URL, options: CrawlOptions): boolean { const sameHost = url.hostname === root.hostname || (options.includeSubdomains === true && url.hostname.endsWith(`.${root.hostname}`)); if (!sameHost || !["http:", "https:"].includes(url.protocol)) return false; const value = url.href; if (options.include?.length && !options.include.some((p) => p.test(value))) return false; return !options.exclude?.some((p) => p.test(value)); }
async function fetchPageWithRedirects(url: string, signal: AbortSignal, maxResponseBytes = DEFAULT_CRAWL_BUDGET.maxResponseBytes) { const secure = await safeFetch(url, { signal, policy: { maxResponseBytes, profile: crawlNetworkProfile() } }); const response = { status: secure.status, ok: secure.ok, headers: new Headers(secure.headers), arrayBuffer: async () => secure.body.buffer.slice(secure.body.byteOffset, secure.body.byteOffset + secure.body.byteLength) }; return { response, chain: secure.redirectChain, finalUrl: secure.url }; }

export async function crawlSite(startUrl: string, options: Partial<CrawlOptions> = {}): Promise<CrawlResult> {
  const budget = { ...DEFAULT_CRAWL_BUDGET, ...options.budget }; const settings: CrawlOptions = { budget, respectRobots: true, ...options }; const root = new URL(normalizeCrawlUrl(startUrl)); const started = Date.now();
  const previous = settings.resume?.records ?? []; const records = new Map(previous.map((record) => [record.normalizedUrl, record])); const queued = new Map<string, number>([[root.href, 0]]); const seen = new Set(previous.map((record) => record.normalizedUrl));
  const robotsUrl = new URL("/robots.txt", root).href; const robotsResponse = await safeFetch(robotsUrl, { signal: AbortSignal.timeout(Math.min(10_000, budget.maxDurationMs)), policy: { maxResponseBytes: Math.min(512_000, budget.maxResponseBytes), profile: crawlNetworkProfile() } }).catch(() => undefined); const robots = robotsResponse?.ok ? robotsResponse.text() : ""; const parsedRobots = parseRobotsTxt(robots); const sitemapUrls = [...parsedRobots.sitemaps]; if (!sitemapUrls.length) sitemapUrls.push(new URL("/sitemap.xml", root).href);
  let cancelled = false; let exhausted = false;
  const progress = (current?: string) => { const value = { discovered: seen.size + queued.size, completed: records.size, queued: queued.size, elapsedMs: Date.now() - started, current }; settings.onProgress?.(value); return value; };
  const visit = async (url: string, depth: number) => {
    if (settings.signal?.aborted) { cancelled = true; return; } const normalizedUrl = normalizeCrawlUrl(url); if (seen.has(normalizedUrl) || records.size >= budget.maxPages) return; seen.add(normalizedUrl);
    const parsed = new URL(normalizedUrl); const blocked = settings.respectRobots !== false && !isRobotsAllowed(`${parsed.pathname}${parsed.search}`, parsedRobots); if (blocked) { records.set(normalizedUrl, { url, normalizedUrl, status: 0, depth, title: "", description: "", canonical: "", indexable: false, blockedByRobots: true, links: [], issueCount: 1, bytes: 0 }); progress(url); return; }
    try { const signal = AbortSignal.any([AbortSignal.timeout(Math.min(20_000, budget.maxDurationMs)), settings.signal ?? new AbortController().signal]); const fetched = await fetchPageWithRedirects(normalizedUrl, signal); const { response } = fetched; const declared = Number(response.headers.get("content-length") ?? 0); if (declared > budget.maxResponseBytes) throw new Error(`Response exceeds ${budget.maxResponseBytes} byte budget`); const buffer = Buffer.from(await response.arrayBuffer()); if (buffer.length > budget.maxResponseBytes) throw new Error(`Response exceeds ${budget.maxResponseBytes} byte budget`); const html = buffer.toString("utf8"); const links = [...html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"'#]+)["']/gi)].map((m) => { try { return normalizeCrawlUrl(new URL(m[1], fetched.finalUrl).href); } catch { return ""; } }).filter(Boolean); const seo = analyzeSeoHtml(html, fetched.finalUrl, response.status, fetched.chain); const canonical = extract(html, /<link\b[^>]*rel=["']canonical["'][^>]*href=["']([^"']*)["'][^>]*>/i); const metaRobots = extract(html, /<meta\b[^>]*name=["']robots["'][^>]*content=["']([^"']*)["'][^>]*>/i); const hreflang = [...html.matchAll(/<link\b[^>]*rel=["']alternate["'][^>]*hreflang=["']([^"']+)["'][^>]*href=["']([^"']+)["'][^>]*>/gi)].map((match) => ({ language: match[1], url: new URL(match[2], fetched.finalUrl).href })); const xRobotsTag = response.headers.get("x-robots-tag") ?? ""; const record: CrawlRecord = { url, normalizedUrl, finalUrl: fetched.finalUrl, status: response.status, depth, title: extract(html, /<title[^>]*>([\s\S]*?)<\/title>/i), description: extract(html, /<meta\b[^>]*name=["']description["'][^>]*content=["']([^"']*)["'][^>]*>/i), canonical, indexable: response.ok && !/\bnoindex\b/i.test(`${metaRobots},${xRobotsTag}`) && !seo.findings.some((f: SeoFinding) => ["canonical-invalid", "document-status"].includes(f.ruleId)), blockedByRobots: false, links: [...new Set(links)], issueCount: seo.findings.length, bytes: buffer.length, mimeType: response.headers.get("content-type")?.split(";")[0] ?? "", xRobotsTag, metaRobots, redirectChain: fetched.chain, hreflang, bodyText: html.replace(/<script\b[\s\S]*?<\/script>/gi, " ").replace(/<style\b[\s\S]*?<\/style>/gi, " ").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 5000) }; records.set(normalizedUrl, record); if (depth < budget.maxDepth) for (const link of record.links) { const candidate = new URL(link); if (allowed(candidate, root, settings) && !seen.has(link) && !queued.has(link)) queued.set(link, depth + 1); } }
    catch (error) { const cause = error instanceof Error && error.cause ? ` (${String(error.cause)})` : ""; records.set(normalizedUrl, { url, normalizedUrl, status: 0, depth, title: "", description: "", canonical: "", indexable: false, blockedByRobots: false, links: [], issueCount: 1, bytes: 0, error: `${error instanceof Error ? error.message : String(error)}${cause}` }); }
    progress(url);
  };
  while (queued.size && records.size < budget.maxPages) { if (settings.signal?.aborted) { cancelled = true; break; } if (Date.now() - started >= budget.maxDurationMs) { exhausted = true; break; } const batch = [...queued.entries()].slice(0, Math.max(1, Math.min(10, budget.concurrency))); batch.forEach(([url]) => queued.delete(url)); await Promise.all(batch.map(([url, depth]) => visit(url, depth))); if (budget.delayMs) await new Promise((resolve) => setTimeout(resolve, Math.min(budget.delayMs, 5_000))); }
  if (records.size >= budget.maxPages && queued.size) exhausted = true;
  const list = [...records.values()]; const issues: CrawlSiteIssue[] = []; const group = (field: "title" | "description") => { const values = new Map<string, string[]>(); list.filter((r) => r[field]).forEach((r) => values.set(r[field], [...(values.get(r[field]) ?? []), r.url])); for (const [value, urls] of values) if (urls.length > 1) issues.push({ ruleId: `duplicate-${field}`, message: `Duplicate ${field}: ${value}`, urls, severity: "medium" }); }; group("title"); group("description");
  for (const record of list) { if (record.status >= 400 || record.status === 0) issues.push({ ruleId: "broken-url", message: `${record.url} returned ${record.status || record.error}`, urls: [record.url], severity: "high" }); if (record.depth > 3) issues.push({ ruleId: "excessive-depth", message: `${record.url} is ${record.depth} clicks deep`, urls: [record.url], severity: "low" }); if (record.canonical && normalizeCrawlUrl(new URL(record.canonical, record.url).href) !== record.normalizedUrl) issues.push({ ruleId: "canonical-conflict", message: `${record.url} canonicalizes elsewhere`, urls: [record.url, record.canonical], severity: "medium" }); }
  const sitemapFound = new Set<string>(); for (const sitemap of sitemapUrls.slice(0, 10)) { try { const xml = await (await fetch(sitemap, { signal: AbortSignal.timeout(10_000) })).text(); const validation = validateSitemapXml(xml, sitemap); validation.urls.forEach((value) => { try { sitemapFound.add(normalizeCrawlUrl(value)); } catch { /* reported by validation */ } }); validation.findings.forEach((finding) => issues.push({ ruleId: finding.ruleId, message: finding.message, urls: finding.urls, severity: finding.severity })); } catch { issues.push({ ruleId: "sitemap-unavailable", message: `Sitemap could not be fetched: ${sitemap}`, urls: [sitemap], severity: "medium" }); } }
  const signals: TechnicalPageSignal[] = list.filter((record) => record.status > 0).map((record) => ({ url: record.normalizedUrl, status: record.status, finalUrl: record.finalUrl ?? record.normalizedUrl, redirectChain: record.redirectChain ?? [], mimeType: record.mimeType ?? "", xRobotsTag: record.xRobotsTag ?? "", metaRobots: record.metaRobots ?? "", canonical: record.canonical, hreflang: record.hreflang ?? [], title: record.title, bodyText: record.bodyText ?? "" })); analyzeTechnicalSignals(signals).forEach((finding) => issues.push({ ruleId: finding.ruleId, message: `${finding.message} | ${finding.remediation}`, urls: finding.urls, severity: finding.severity }));
  for (const url of sitemapFound) if (!records.has(url)) issues.push({ ruleId: "sitemap-undiscovered", message: "Sitemap URL was not discovered by crawling", urls: [url], severity: "low" }); const linked = new Set(list.flatMap((r) => r.links)); for (const record of list) if (record.depth > 0 && sitemapFound.has(record.normalizedUrl) && !linked.has(record.normalizedUrl)) issues.push({ ruleId: "likely-orphan", message: "Sitemap page has no discovered internal link", urls: [record.url], severity: "medium" });
  return { startedAt: new Date(started).toISOString(), completedAt: new Date().toISOString(), startUrl: root.href, status: cancelled ? "cancelled" : exhausted ? "budget-exhausted" : "completed", records: list, issues, sitemapUrls, progress: progress() };
}
