import fs from "node:fs/promises";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { glob } from "glob";
const exec = promisify(execFile);

export type TestFramework = "jest" | "vitest" | "playwright" | "react-testing-library";
export interface TestMap { frameworks: TestFramework[]; tests: string[]; related: Record<string, string[]> }
export interface CoverageRisk { file: string; lines: number; branches: number; functions: number; risk: "low" | "medium" | "high" }
export async function detectTests(root: string, sources: string[] = []): Promise<TestMap> { const pkg = JSON.parse(await fs.readFile(path.join(root, "package.json"), "utf8")) as { dependencies?: Record<string, string>; devDependencies?: Record<string, string> }; const deps = { ...pkg.dependencies, ...pkg.devDependencies }; const frameworks: TestFramework[] = []; if (deps.jest || await exists(root, "jest.config.js") || await exists(root, "jest.config.ts")) frameworks.push("jest"); if (deps.vitest || await exists(root, "vitest.config.ts")) frameworks.push("vitest"); if (deps["@playwright/test"] || await exists(root, "playwright.config.ts")) frameworks.push("playwright"); if (deps["@testing-library/react"]) frameworks.push("react-testing-library"); const tests = (await glob("**/*.{test,spec}.{js,jsx,ts,tsx}", { cwd: root, nodir: true, ignore: ["**/node_modules/**", "**/dist/**"] })).map((f) => f.replace(/\\/g, "/")); const related: Record<string, string[]> = {}; for (const source of sources) { const stem = path.basename(source).replace(/\.[^.]+$/, ""); related[source] = []; for (const test of tests) { const content = await fs.readFile(path.join(root, test), "utf8").catch(() => ""); if (path.basename(test).startsWith(`${stem}.`) || content.includes(stem)) related[source].push(test); } } return { frameworks, tests, related }; }
async function exists(root: string, name: string) { return fs.access(path.join(root, name)).then(() => true).catch(() => false); }
export async function importCoverage(root: string, file = "coverage/coverage-summary.json"): Promise<CoverageRisk[]> { const data = JSON.parse(await fs.readFile(path.join(root, file), "utf8")) as Record<string, Record<string, { pct?: number }>>; return Object.entries(data).filter(([name]) => name !== "total").map(([name, metrics]) => { const lines = metrics.lines?.pct ?? 0, branches = metrics.branches?.pct ?? 0, functions = metrics.functions?.pct ?? 0, minimum = Math.min(lines, branches, functions); return { file: path.isAbsolute(name) ? path.relative(root, name).replace(/\\/g, "/") : name, lines, branches, functions, risk: minimum < 50 ? "high" : minimum < 80 ? "medium" : "low" }; }); }
export async function detectFlakyTest(root: string, command: string, args: string[], repetitions = 3, timeoutMs = 60_000) { const outcomes: Array<{ passed: boolean; output: string }> = []; for (let i = 0; i < Math.max(2, Math.min(10, repetitions)); i++) { try { const result = await exec(command, args, { cwd: root, timeout: timeoutMs, maxBuffer: 2_000_000 }); outcomes.push({ passed: true, output: `${result.stdout}${result.stderr}`.slice(-2000) }); } catch (error) { const value = error as { stdout?: string; stderr?: string }; outcomes.push({ passed: false, output: `${value.stdout ?? ""}${value.stderr ?? ""}`.slice(-2000) }); } } return { flaky: outcomes.some((o) => o.passed) && outcomes.some((o) => !o.passed), outcomes }; }
export function testHealth(mapping: TestMap, coverage: CoverageRisk[]) { const tested = Object.values(mapping.related).filter((tests) => tests.length).length; const total = Object.keys(mapping.related).length; const coveragePenalty = coverage.reduce((sum, item) => sum + (item.risk === "high" ? 8 : item.risk === "medium" ? 3 : 0), 0); const mappingPenalty = total ? Math.round((1 - tested / total) * 40) : 0; return { score: Math.max(0, 100 - coveragePenalty - mappingPenalty), testedSources: tested, totalSources: total, gaps: coverage.filter((item) => item.risk !== "low") }; }
export function verificationGate(input: { requiredPassed: boolean; runtimePassed: boolean; visualDifference?: number; visualThreshold?: number }) { const reasons: string[] = []; if (!input.requiredPassed) reasons.push("Required tests failed"); if (!input.runtimePassed) reasons.push("Runtime checks failed"); if ((input.visualDifference ?? 0) > (input.visualThreshold ?? 0.01)) reasons.push(`Visual difference ${input.visualDifference} exceeds threshold ${input.visualThreshold ?? 0.01}`); return { passed: reasons.length === 0, reasons }; }
