import fs from "node:fs/promises";
import path from "node:path";
import { createHash, randomUUID } from "node:crypto";
import type { PersistencePort } from "../persistence/port";
import type { ArtifactRef, ArtifactStore } from "./artifactStore";
export interface ArtifactScope { tenantId: string; projectId: string; retainUntil?: string }
export class FilesystemArtifactStore implements ArtifactStore {
  constructor(private readonly root: string, private readonly database: PersistencePort, private readonly scope: ArtifactScope, private readonly maxBytes = 50 * 1024 * 1024) {}
  async put(bytes: Uint8Array, mediaType: string): Promise<ArtifactRef> { if (bytes.byteLength > this.maxBytes) throw new Error(`Artifact exceeds ${this.maxBytes} byte limit`); const sha256 = createHash("sha256").update(bytes).digest("hex"); const key = path.join(this.scope.tenantId, this.scope.projectId, sha256.slice(0, 2), sha256); const target = path.resolve(this.root, key); const root = path.resolve(this.root); if (!target.startsWith(`${root}${path.sep}`)) throw new Error("Invalid artifact scope"); await fs.mkdir(path.dirname(target), { recursive: true }); try { await fs.access(target); } catch { const temporary = `${target}.${process.pid}.${randomUUID()}.partial`; try { await fs.writeFile(temporary, bytes, { flag: "wx" }); const check = createHash("sha256").update(await fs.readFile(temporary)).digest("hex"); if (check !== sha256) throw new Error("Artifact checksum mismatch during upload"); await fs.rename(temporary, target); } finally { await fs.rm(temporary, { force: true }).catch(() => undefined); } } const id = randomUUID(); await this.database.execute("INSERT INTO artifacts(id,tenant_id,project_id,sha256,size_bytes,media_type,storage_key,created_at,retain_until) VALUES(?,?,?,?,?,?,?,?,?)", [id, this.scope.tenantId, this.scope.projectId, sha256, bytes.byteLength, mediaType, key.replace(/\\/g, "/"), new Date().toISOString(), this.scope.retainUntil ?? null]); return { id, sha256, mediaType, size: bytes.byteLength } as ArtifactRef; }
  async get(id: string): Promise<Uint8Array | undefined> { const rows = await this.database.query<Record<string, unknown>>("SELECT storage_key,sha256 FROM artifacts WHERE id=? AND tenant_id=? AND project_id=? AND deleted_at IS NULL", [id, this.scope.tenantId, this.scope.projectId]); if (!rows[0]) return undefined; const file = path.resolve(this.root, String(rows[0].storage_key)); if (!file.startsWith(`${path.resolve(this.root)}${path.sep}`)) throw new Error("Artifact key escaped storage root"); const bytes = await fs.readFile(file); const checksum = createHash("sha256").update(bytes).digest("hex"); if (checksum !== rows[0].sha256) throw new Error("Artifact checksum mismatch"); return bytes; }
}
export interface S3ClientPort { putObject(input: { bucket: string; key: string; body: Uint8Array; contentType: string; checksumSha256: string }): Promise<void>; getObject(input: { bucket: string; key: string }): Promise<Uint8Array | undefined> }
export class S3ArtifactStore implements ArtifactStore { constructor(private readonly client: S3ClientPort, private readonly bucket: string, private readonly database: PersistencePort, private readonly scope: ArtifactScope, private readonly maxBytes = 50 * 1024 * 1024) {} async put(bytes: Uint8Array, mediaType: string): Promise<ArtifactRef> { if (bytes.byteLength > this.maxBytes) throw new Error("Artifact size limit exceeded"); const sha256 = createHash("sha256").update(bytes).digest("hex"); const key = `${this.scope.tenantId}/${this.scope.projectId}/${sha256.slice(0,2)}/${sha256}`; await this.client.putObject({ bucket: this.bucket, key, body: bytes, contentType: mediaType, checksumSha256: sha256 }); const id = randomUUID(); await this.database.execute("INSERT INTO artifacts(id,tenant_id,project_id,sha256,size_bytes,media_type,storage_key,created_at) VALUES(?,?,?,?,?,?,?,?)", [id,this.scope.tenantId,this.scope.projectId,sha256,bytes.byteLength,mediaType,key,new Date().toISOString()]); return { id,sha256,mediaType }; } async get(id: string) { const rows = await this.database.query<Record<string,unknown>>("SELECT storage_key,sha256 FROM artifacts WHERE id=? AND tenant_id=? AND project_id=? AND deleted_at IS NULL",[id,this.scope.tenantId,this.scope.projectId]); if(!rows[0]) return undefined; const bytes=await this.client.getObject({bucket:this.bucket,key:String(rows[0].storage_key)}); if(bytes && createHash("sha256").update(bytes).digest("hex")!==rows[0].sha256) throw new Error("Artifact checksum mismatch"); return bytes; } }
