import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { PersistencePort } from "../persistence/port";
export class RetentionService {
  constructor(private readonly database: PersistencePort, private readonly artifactRoot: string) {}
  async setPolicy(tenantId: string, projectId: string | undefined, days: number, legalHold = false) { if (!Number.isInteger(days) || days < 0 || days > 3650) throw new Error("Retention days must be between 0 and 3650"); await this.database.execute("INSERT INTO retention_policies(id,tenant_id,project_id,days,legal_hold) VALUES(?,?,?,?,?)", [randomUUID(), tenantId, projectId ?? null, days, legalHold ? 1 : 0]); }
  async apply(tenantId: string, now = new Date()): Promise<{ deleted: number; held: number }> { const rows = await this.database.query<Record<string, unknown>>("SELECT id,storage_key,legal_hold FROM artifacts WHERE tenant_id=? AND deleted_at IS NULL AND retain_until IS NOT NULL AND retain_until<?", [tenantId, now.toISOString()]); let deleted = 0, held = 0; for (const row of rows) { if (Number(row.legal_hold)) { held++; continue; } const target = path.resolve(this.artifactRoot, String(row.storage_key)); if (!target.startsWith(`${path.resolve(this.artifactRoot)}${path.sep}`)) throw new Error("Artifact retention path escaped root"); await fs.rm(target, { force: true }); await this.database.execute("UPDATE artifacts SET deleted_at=? WHERE tenant_id=? AND id=?", [now.toISOString(), tenantId, row.id]); deleted++; } return { deleted, held }; }
  async requestProjectDeletion(tenantId: string, projectId: string) { const id = randomUUID(); await this.database.transaction(async (tx) => { await tx.execute("INSERT INTO deletion_requests(id,tenant_id,project_id,status,requested_at) VALUES(?,?,?,?,?)", [id,tenantId,projectId,"queued",new Date().toISOString()]); await tx.execute("INSERT INTO outbox(id,tenant_id,aggregate_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)", [randomUUID(),tenantId,id,"project.deletion_requested",JSON.stringify({projectId}),new Date().toISOString()]); }); return id; }
  async processProjectDeletion(tenantId: string, requestId: string) { const requests = await this.database.query<Record<string,unknown>>("SELECT * FROM deletion_requests WHERE tenant_id=? AND id=? AND status='queued'",[tenantId,requestId]); const request=requests[0]; if(!request) throw new Error("Deletion request not found"); const projectId=String(request.project_id); const artifacts=await this.database.query<Record<string,unknown>>("SELECT id,storage_key,legal_hold FROM artifacts WHERE tenant_id=? AND project_id=? AND deleted_at IS NULL",[tenantId,projectId]); let deleted=0,held=0; for(const artifact of artifacts){ if(Number(artifact.legal_hold)){held++;continue;} const target=path.resolve(this.artifactRoot,String(artifact.storage_key)); if(!target.startsWith(`${path.resolve(this.artifactRoot)}${path.sep}`)) throw new Error("Artifact deletion path escaped root"); await fs.rm(target,{force:true}); await this.database.execute("UPDATE artifacts SET deleted_at=? WHERE tenant_id=? AND id=?",[new Date().toISOString(),tenantId,artifact.id]); deleted++; } await this.database.transaction(async(tx)=>{await tx.execute("UPDATE projects SET deleted_at=? WHERE tenant_id=? AND id=?",[new Date().toISOString(),tenantId,projectId]); await tx.execute("UPDATE deletion_requests SET status='completed',completed_at=?,verification_json=? WHERE tenant_id=? AND id=?",[new Date().toISOString(),JSON.stringify({artifactsDeleted:deleted,artifactsHeld:held}),tenantId,requestId]); await tx.execute("INSERT INTO outbox(id,tenant_id,aggregate_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)",[randomUUID(),tenantId,requestId,"project.deleted",JSON.stringify({projectId,deleted,held}),new Date().toISOString()]);}); return {deleted,held}; }
}
