import { randomUUID } from "node:crypto";
import type { PersistencePort } from "../persistence/port";
import type { DurableJob } from "../persistence/repositories";
export class DurableQueue {
  constructor(private readonly database: PersistencePort, private readonly tenantId: string) {}
  async lease(workerId: string, leaseMs = 30_000): Promise<DurableJob | undefined> { const now = new Date(); const expires = new Date(now.getTime() + leaseMs).toISOString(); return this.database.transaction(async (tx) => { const rows = await tx.query<Record<string, unknown>>("SELECT id FROM jobs WHERE tenant_id=? AND status='queued' ORDER BY created_at LIMIT 1", [this.tenantId]); if (!rows[0]) return undefined; const id = String(rows[0].id); const changed = await tx.execute("UPDATE jobs SET status='leased',lease_owner=?,lease_expires_at=?,updated_at=? WHERE tenant_id=? AND id=? AND status='queued'", [workerId, expires, now.toISOString(), this.tenantId, id]); if (!changed.changes) return undefined; const attemptRows = await tx.query<{ count: number }>("SELECT COUNT(*) AS count FROM job_attempts WHERE job_id=?", [id]); await tx.execute("INSERT INTO job_attempts(id,tenant_id,job_id,attempt_no,status,started_at) VALUES(?,?,?,?,?,?)", [randomUUID(), this.tenantId, id, Number(attemptRows[0]?.count ?? 0) + 1, "leased", now.toISOString()]); return (await tx.query<Record<string, unknown>>("SELECT * FROM jobs WHERE tenant_id=? AND id=?", [this.tenantId, id]))[0] as unknown as DurableJob; }); }
  async start(jobId: string, workerId: string) { return (await this.database.execute("UPDATE jobs SET status='running',updated_at=? WHERE tenant_id=? AND id=? AND status='leased' AND lease_owner=?", [new Date().toISOString(), this.tenantId, jobId, workerId])).changes > 0; }
  async heartbeat(jobId: string, workerId: string, leaseMs = 30_000) { const expires = new Date(Date.now() + leaseMs).toISOString(); return (await this.database.execute("UPDATE jobs SET lease_expires_at=?,updated_at=? WHERE tenant_id=? AND id=? AND status IN ('leased','running') AND lease_owner=?", [expires, new Date().toISOString(), this.tenantId, jobId, workerId])).changes > 0; }
  async recoverExpired(now = new Date()): Promise<number> { const result = await this.database.execute("UPDATE jobs SET status='queued',lease_owner=NULL,lease_expires_at=NULL,updated_at=? WHERE tenant_id=? AND status IN ('leased','running') AND lease_expires_at<?", [now.toISOString(), this.tenantId, now.toISOString()]); return result.changes; }
  async acknowledgeCancellation(jobId: string, workerId: string) { return (await this.database.execute("UPDATE jobs SET status='cancelled',lease_owner=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE tenant_id=? AND id=? AND lease_owner=? AND cancel_requested_at IS NOT NULL AND status IN ('leased','running')", [new Date().toISOString(), new Date().toISOString(), this.tenantId, jobId, workerId])).changes > 0; }
}
