import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { api } from "../api/client";
import { localizeStatus, useLanguage, type Lang } from "../i18n";
import { useNotify } from "../shell/Notifications";

type Finding = { id: string; ruleId?: string; message: string; severity: string; meta?: { seoCategory?: string }; evidence?: { url?: string } };
type SeoProject = { id: string; kind: "seo"; name: string; environments: Array<{ id: string; name: string; baseUrl: string }> };
type SeoResult = { schemaVersion: 1; url: string; findings: Finding[]; healthScore?: number };
type CrawlResult = { records: Array<{ url: string; status: number; title: string; depth: number; indexable: boolean; issueCount: number }>; issues: Array<{ ruleId: string; message: string; severity: string; urls: string[] }>; status: string; progress: { completed: number; discovered: number } };
type SeoProfile = { name: string; businessType: string; domains: string[]; languages: string[]; markets: string[]; conversions: string[] };
type Tab = "overview" | "technical" | "content" | "crawler" | "profile" | "strategy" | "monitoring";

const tabIds: Array<[Tab,string]> = [["overview","⌂"],["technical","⚙"],["content","◇"],["crawler","↗"],["profile","▣"],["strategy","◎"],["monitoring","⌁"]];
const labels = {
  fa: {
    tabs: { overview:"نمای کلی", technical:"سئوی فنی", content:"محتوا و موجودیت‌ها", crawler:"خزنده سایت", profile:"پروفایل پروژه", strategy:"کلیدواژه‌ها و کمپین‌ها", monitoring:"پایش" },
    eyebrow:"فضای کاری یکپارچه سئو", title:"آزمایشگاه و مرکز فرماندهی سئو", subtitle:"ممیزی، خزش، اولویت‌بندی و پایش یک سایت در یک فضای کاری.",
    health:"سلامت سایت", firstAudit:"اولین ممیزی را اجرا کنید", findings:"یافته", urgent:"فوری", project:"پروژه", website:"نشانی وب‌سایت", auditing:"در حال ممیزی…", runAudit:"اجرای ممیزی کامل", production:"محیط اصلی",
    score:"امتیاز سلامت", technicalFindings:"یافته‌های فنی", contentSignals:"سیگنال‌های محتوا", crawledPages:"صفحات خزش‌شده", actions:"اقدام‌های اولویت‌دار", actionsSub:"کارهای با بیشترین اثر در تمام سامانه‌های سئو",
    coverage:"پوشش فضای کاری", coverageSub:"همه ابزارهای متصل به این پروژه سئو", ready:"آماده", notRun:"اجرا نشده", analyzed:"تحلیل‌شده", waiting:"در انتظار",
    technicalTitle:"سئوی فنی و ایندکس‌پذیری", technicalSub:"متادیتا، canonical، دستورهای خزش، داده ساخت‌یافته و رندر جاوااسکریپت",
    contentTitle:"هوشمندی محتوا و موجودیت‌ها", contentSub:"عنوان صفحات، توضیحات، پوشش معنایی و آمادگی موجودیت‌ها",
    crawlerTitle:"خزنده کنترل‌شده سئو", crawlerSub:"کشف صفحات با رعایت robots.txt، محافظت SSRF و محدودیت دقیق منابع", crawling:"در حال خزش تا ۲۵ صفحه…", startCrawl:"شروع خزش کنترل‌شده",
    pages:"صفحات", siteIssues:"مشکلات سایت", status:"وضعیت", page:"صفحه", depth:"عمق", indexable:"قابل ایندکس", issues:"مشکلات", yes:"بله", no:"خیر",
    profileTitle:"پروفایل پروژه سئو", profileSub:"هویت، دامنه، بازار و اهداف تبدیل پروژه را یک‌جا نگهداری کنید.", saveProfile:"ذخیره پروفایل", saved:"پروفایل ذخیره شد", projectName:"نام پروژه", businessType:"نوع کسب‌وکار", domains:"دامنه‌ها", languages:"زبان‌ها", markets:"بازارها", conversions:"تبدیل‌ها",
    strategyTitle:"کلیدواژه‌ها، موضوعات و کمپین‌ها", strategySub:"شواهد ممیزی را به برنامه اجرایی اولویت‌بندی‌شده سئو تبدیل کنید", immediate:"فوری", resolve:"یافته پراهمیت را برطرف کنید", blockers:"ابتدا موانع فنی و ریسک‌های ایندکس‌پذیری را برطرف کنید.", next:"مرحله بعد", metadata:"پوشش متادیتا را بهتر کنید", opportunities:"فرصت متادیتا شناسایی شد.", ongoing:"مستمر", authority:"اعتبار موضوعی و موجودیتی بسازید", authoritySub:"از پوشش خزش و روندهای پایش به‌عنوان شواهد کمپین استفاده کنید.",
    monitoringTitle:"پایش، آزمایش‌ها و دوقلوی دیجیتال", monitoringSub:"سلامت را در طول زمان پایش و ممیزی‌ها را مقایسه کنید", noHistory:"تاریخچه ممیزی اینجا نمایش داده می‌شود.", auditDone:"ممیزی سئو تکمیل شد", crawlDone:"خزش سایت تکمیل شد", empty:"برای نمایش این بخش یک ممیزی اجرا کنید.", signal:"سیگنال سئو"
  },
  en: {
    tabs:{overview:"Overview",technical:"Technical SEO",content:"Content & Entities",crawler:"Site Crawler",profile:"Project Profile",strategy:"Keywords & Campaigns",monitoring:"Monitoring"},
    eyebrow:"UNIFIED SEO WORKSPACE",title:"SEO Audit Lab & Command Center",subtitle:"Audit, crawl, prioritize and monitor one site from a single workspace.",health:"Site health",firstAudit:"Run your first audit",findings:"findings",urgent:"urgent",project:"Project",website:"Website URL",auditing:"Auditing…",runAudit:"Run full audit",production:"Production",
    score:"Health score",technicalFindings:"Technical findings",contentSignals:"Content signals",crawledPages:"Crawled pages",actions:"Priority actions",actionsSub:"Highest-impact work across all SEO systems",coverage:"Workspace coverage",coverageSub:"Everything connected to this SEO project",ready:"Ready",notRun:"Not run",analyzed:"Analyzed",waiting:"Waiting",
    technicalTitle:"Technical SEO & Indexability",technicalSub:"Metadata, canonicalization, crawl directives, structured data and JavaScript rendering",contentTitle:"Content & Entity Intelligence",contentSub:"Page titles, descriptions, semantic coverage and entity readiness",
    crawlerTitle:"Controlled SEO Crawler",crawlerSub:"Robots-aware discovery with SSRF protection and strict resource budgets",crawling:"Crawling up to 25 pages…",startCrawl:"Start controlled crawl",pages:"Pages",siteIssues:"Site issues",status:"Status",page:"Page",depth:"Depth",indexable:"Indexable",issues:"Issues",yes:"Yes",no:"No",
    profileTitle:"SEO Project Profile",profileSub:"Keep project identity, domains, markets and conversion goals together.",saveProfile:"Save profile",saved:"Profile saved",projectName:"Project name",businessType:"Business type",domains:"Domains",languages:"Languages",markets:"Markets",conversions:"Conversions",
    strategyTitle:"Keywords, Topics & Campaigns",strategySub:"Turn audit evidence into a prioritized SEO delivery plan",immediate:"Immediate",resolve:"high-impact findings to resolve",blockers:"Technical blockers and indexability risks come first.",next:"Next",metadata:"Improve metadata coverage",opportunities:"metadata opportunities detected.",ongoing:"Ongoing",authority:"Build topic and entity authority",authoritySub:"Use crawl coverage and monitoring trends as campaign evidence.",
    monitoringTitle:"Monitoring, Experiments & Digital Twin",monitoringSub:"Track health over time and compare every audit",noHistory:"Audit history will appear here.",auditDone:"SEO audit completed",crawlDone:"Site crawl completed",empty:"Run an audit to populate this section.",signal:"SEO signal"
  }
} as const;

const splitList = (value:string) => value.split(",").map(item=>item.trim()).filter(Boolean);
const profileKey = "seo-project-profile";

export function SeoWorkspacePage() {
  const lang=useLanguage(); const t=labels[lang]; const fa=lang==="fa";
  const [name,setName]=useState(fa?"وب‌سایت":"Website"); const [url,setUrl]=useState(""); const [project,setProject]=useState<SeoProject>(); const [result,setResult]=useState<SeoResult>(); const [crawl,setCrawl]=useState<CrawlResult>(); const [tab,setTab]=useState<Tab>("overview"); const [busy,setBusy]=useState(false); const [crawlBusy,setCrawlBusy]=useState(false); const [history,setHistory]=useState<Array<{at:string;score:number;findings:number;url:string}>>([]); const [profile,setProfile]=useState<SeoProfile>(()=>{try{return JSON.parse(localStorage.getItem(profileKey)||"null")||{name:"",businessType:"saas",domains:[],languages:["fa"],markets:[],conversions:[]}}catch{return{name:"",businessType:"saas",domains:[],languages:["fa"],markets:[],conversions:[]}}}); const [profileSaved,setProfileSaved]=useState(()=>Boolean(localStorage.getItem(profileKey))); const notify=useNotify();
  useEffect(()=>{ try { setHistory(JSON.parse(localStorage.getItem("seo-audit-history")||"[]")); } catch { setHistory([]); } },[]);
  const grouped=useMemo(()=>(result?.findings??[]).reduce<Record<string,Finding[]>>((groups,finding)=>{const key=finding.meta?.seoCategory??(finding.ruleId?.includes("canonical")?"indexability":"technical");(groups[key]??=[]).push(finding);return groups;},{}),[result]);
  const tabs=tabIds.map(([id,icon])=>[id,t.tabs[id],icon] as const);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);try{const nextProject=await api<SeoProject>("/api/v1/platform/projects",{method:"POST",body:JSON.stringify({schemaVersion:1,kind:"seo",name,environments:[{name:"production",baseUrl:url}]})});setProject(nextProject);setProfile(current=>({...current,name:current.name||name,domains:current.domains.length?current.domains:[url]}));const environment=nextProject.environments[0];const audit=await api<SeoResult>("/api/v1/seo/audits",{method:"POST",body:JSON.stringify({schemaVersion:1,kind:"seo",seoProjectId:nextProject.id,environmentId:environment.id,options:{lighthouse:true}})});setResult(audit);const item={at:new Date().toISOString(),score:audit.healthScore??0,findings:audit.findings.length,url:audit.url};const next=[item,...history].slice(0,20);setHistory(next);localStorage.setItem("seo-audit-history",JSON.stringify(next));notify(t.auditDone);}catch(error){notify(error instanceof Error?error.message:String(error),"error");}finally{setBusy(false)}}
  async function runCrawl(){if(!project)return;setCrawlBusy(true);try{const environment=project.environments[0];const data=await api<CrawlResult>("/api/v1/seo/crawls",{method:"POST",body:JSON.stringify({schemaVersion:1,seoProjectId:project.id,environmentId:environment.id,options:{maxPages:25,maxDepth:3}})});setCrawl(data);notify(t.crawlDone);}catch(error){notify(error instanceof Error?error.message:String(error),"error");}finally{setCrawlBusy(false)}}
  function saveProfile(){localStorage.setItem(profileKey,JSON.stringify(profile));setProfileSaved(true);notify(t.saved)}
  const score=result?.healthScore??0; const severe=result?.findings.filter(item=>item.severity==="high"||item.severity==="critical").length??0;
  return <main className="seo-hub"><header className="seo-hero"><div><span className="eyebrow">{t.eyebrow}</span><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="seo-health"><span>{t.health}</span><strong>{result?score:"—"}</strong><small>{result?`${result.findings.length} ${t.findings} · ${severe} ${t.urgent}`:t.firstAudit}</small></div></header>
    <section className="seo-project-bar"><form onSubmit={submit}><label>{t.project}<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="seo-url">{t.website}<input type="url" required placeholder="https://example.com" value={url} onChange={e=>setUrl(e.target.value)}/></label><button disabled={busy}>{busy?t.auditing:t.runAudit}</button></form>{project?<div className="seo-context"><i/><span>{project.name}</span><code>{project.environments[0].baseUrl}</code><em>{t.production}</em></div>:null}</section>
    <nav className="seo-tabs" aria-label={fa?"ابزارهای سئو":"SEO tools"}>{tabs.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><b>{icon}</b><span>{label}</span>{id==="crawler"&&crawl?<small>{crawl.records.length}</small>:null}</button>)}</nav>
    {tab==="overview"?<section className="seo-dashboard"><div className="seo-kpis"><article><span>{t.score}</span><strong>{result?score:"—"}<small>/100</small></strong></article><article><span>{t.technicalFindings}</span><strong>{(grouped.technical?.length??0)+(grouped.indexability?.length??0)}</strong></article><article><span>{t.contentSignals}</span><strong>{(grouped.metadata?.length??0)+(grouped.content?.length??0)}</strong></article><article><span>{t.crawledPages}</span><strong>{crawl?.records.length??0}</strong></article></div><div className="seo-grid"><article className="seo-panel"><header><div><h2>{t.actions}</h2><p>{t.actionsSub}</p></div></header><FindingList findings={result?.findings??[]} lang={lang}/></article><article className="seo-panel seo-system-map"><header><div><h2>{t.coverage}</h2><p>{t.coverageSub}</p></div></header>{tabs.slice(1).map(([id,label])=><button key={id} onClick={()=>setTab(id)}><span>{label}</span><strong>{id==="crawler"?(crawl?t.ready:t.notRun):id==="profile"?(profileSaved?t.ready:t.waiting):result?t.analyzed:t.waiting}</strong></button>)}</article></div></section>:null}
    {tab==="technical"?<ToolPanel title={t.technicalTitle} subtitle={t.technicalSub}><div className="seo-category-grid">{["technical","indexability","metadata","structuredData","social"].map(category=><article key={category}><header><h3>{categoryLabel(category,lang)}</h3><strong>{grouped[category]?.length??0}</strong></header><FindingList findings={grouped[category]??[]} lang={lang}/></article>)}</div></ToolPanel>:null}
    {tab==="content"?<ToolPanel title={t.contentTitle} subtitle={t.contentSub}><FindingList findings={[...(grouped.content??[]),...(grouped.metadata??[]),...(grouped.social??[])]} lang={lang}/></ToolPanel>:null}
    {tab==="crawler"?<ToolPanel title={t.crawlerTitle} subtitle={t.crawlerSub}><button className="seo-run-tool" disabled={!project||crawlBusy} onClick={runCrawl}>{crawlBusy?t.crawling:t.startCrawl}</button>{crawl?<><div className="seo-kpis compact"><article><span>{t.pages}</span><strong>{crawl.records.length}</strong></article><article><span>{t.siteIssues}</span><strong>{crawl.issues.length}</strong></article><article><span>{t.status}</span><strong>{localizeStatus(crawl.status,lang)}</strong></article></div><div className="seo-crawl-table"><table><thead><tr><th>{t.page}</th><th>{t.status}</th><th>{t.depth}</th><th>{t.indexable}</th><th>{t.issues}</th></tr></thead><tbody>{crawl.records.map(row=><tr key={row.url}><td><a href={row.url} target="_blank" rel="noreferrer">{row.title||row.url}</a></td><td>{row.status}</td><td>{row.depth}</td><td>{row.indexable?t.yes:t.no}</td><td>{row.issueCount}</td></tr>)}</tbody></table></div></>:null}</ToolPanel>:null}
    {tab==="profile"?<ToolPanel title={t.profileTitle} subtitle={t.profileSub}><div className="profile-grid"><label>{t.projectName}<input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>{t.businessType}<select value={profile.businessType} onChange={e=>setProfile({...profile,businessType:e.target.value})}>{["saas","ecommerce","marketplace","local","publisher","documentation","multilingual","programmatic"].map(value=><option key={value} value={value}>{businessLabel(value,lang)}</option>)}</select></label><label>{t.domains}<input dir="ltr" value={profile.domains.join(", ")} onChange={e=>setProfile({...profile,domains:splitList(e.target.value)})} placeholder="example.com"/></label><label>{t.languages}<input dir="ltr" value={profile.languages.join(", ")} onChange={e=>setProfile({...profile,languages:splitList(e.target.value)})} placeholder="fa, en-US"/></label><label>{t.markets}<input value={profile.markets.join(", ")} onChange={e=>setProfile({...profile,markets:splitList(e.target.value)})}/></label><label>{t.conversions}<input value={profile.conversions.join(", ")} onChange={e=>setProfile({...profile,conversions:splitList(e.target.value)})}/></label></div><button className="seo-run-tool" onClick={saveProfile}>{profileSaved?"✓ ":null}{t.saveProfile}</button></ToolPanel>:null}
    {tab==="strategy"?<ToolPanel title={t.strategyTitle} subtitle={t.strategySub}><div className="seo-strategy"><article><span>{t.immediate}</span><strong>{severe} {t.resolve}</strong><p>{t.blockers}</p></article><article><span>{t.next}</span><strong>{t.metadata}</strong><p>{grouped.metadata?.length??0} {t.opportunities}</p></article><article><span>{t.ongoing}</span><strong>{t.authority}</strong><p>{t.authoritySub}</p></article></div></ToolPanel>:null}
    {tab==="monitoring"?<ToolPanel title={t.monitoringTitle} subtitle={t.monitoringSub}><div className="seo-history">{history.map(item=><article key={item.at}><time>{new Date(item.at).toLocaleString(fa?"fa-IR":"en-US")}</time><span>{item.url}</span><strong>{item.score}/100</strong><small>{item.findings} {t.findings}</small></article>)}{!history.length?<p className="seo-empty">{t.noHistory}</p>:null}</div></ToolPanel>:null}
  </main>;
}
function ToolPanel({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="seo-panel seo-tool"><header><div><h2>{title}</h2><p>{subtitle}</p></div></header>{children}</section>}
function FindingList({findings,lang}:{findings:Finding[];lang:Lang}){const sorted=[...findings].sort((a,b)=>({critical:0,high:1,medium:2,low:3}[a.severity]??4)-({critical:0,high:1,medium:2,low:3}[b.severity]??4));const t=labels[lang];return <div className="seo-findings">{sorted.map(finding=><article key={finding.id}><i className={`severity ${finding.severity}`}/><div><strong>{finding.message}</strong><small>{finding.ruleId??t.signal}</small></div><em>{severityLabel(finding.severity,lang)}</em></article>)}{!findings.length?<p className="seo-empty">{t.empty}</p>:null}</div>}
function severityLabel(value:string,lang:Lang){if(lang==="en")return value;return({critical:"بحرانی",high:"زیاد",medium:"متوسط",low:"کم"}as Record<string,string>)[value]??value}
function categoryLabel(value:string,lang:Lang){if(lang==="en")return value;return({technical:"فنی",indexability:"ایندکس‌پذیری",metadata:"متادیتا",structuredData:"داده ساخت‌یافته",social:"شبکه‌های اجتماعی"}as Record<string,string>)[value]??value}
function businessLabel(value:string,lang:Lang){if(lang==="en")return value;return({saas:"نرم‌افزار به‌عنوان سرویس",ecommerce:"فروشگاه اینترنتی",marketplace:"بازارگاه",local:"کسب‌وکار محلی",publisher:"ناشر",documentation:"مستندات",multilingual:"چندزبانه",programmatic:"سئوی برنامه‌محور"}as Record<string,string>)[value]??value}
