import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { api } from "../api/client";
import { useNotify } from "../shell/Notifications";

type Finding = { id: string; ruleId?: string; message: string; severity: string; meta?: { seoCategory?: string }; evidence?: { url?: string } };
type SeoProject = { id: string; kind: "seo"; name: string; environments: Array<{ id: string; name: string; baseUrl: string }> };
type SeoResult = { schemaVersion: 1; url: string; findings: Finding[]; healthScore?: number };
type CrawlResult = { records: Array<{ url: string; status: number; title: string; depth: number; indexable: boolean; issueCount: number }>; issues: Array<{ ruleId: string; message: string; severity: string; urls: string[] }>; status: string; progress: { completed: number; discovered: number } };
type Tab = "overview" | "technical" | "content" | "crawler" | "strategy" | "monitoring";
const tabs: Array<[Tab,string,string]> = [["overview","Overview","⌂"],["technical","Technical SEO","⚙"],["content","Content & Entities","◇"],["crawler","Site Crawler","↗"],["strategy","Keywords & Campaigns","◎"],["monitoring","Monitoring","⌁"]];

export function SeoWorkspacePage() {
  const [name,setName]=useState("Website"); const [url,setUrl]=useState(""); const [project,setProject]=useState<SeoProject>(); const [result,setResult]=useState<SeoResult>(); const [crawl,setCrawl]=useState<CrawlResult>(); const [tab,setTab]=useState<Tab>("overview"); const [busy,setBusy]=useState(false); const [crawlBusy,setCrawlBusy]=useState(false); const [history,setHistory]=useState<Array<{at:string;score:number;findings:number;url:string}>>([]); const notify=useNotify();
  useEffect(()=>{ try { setHistory(JSON.parse(localStorage.getItem("seo-audit-history")||"[]")); } catch { setHistory([]); } },[]);
  const grouped=useMemo(()=>(result?.findings??[]).reduce<Record<string,Finding[]>>((groups,finding)=>{const key=finding.meta?.seoCategory??(finding.ruleId?.includes("canonical")?"indexability":"technical");(groups[key]??=[]).push(finding);return groups;},{}),[result]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);try{const nextProject=await api<SeoProject>("/api/v1/platform/projects",{method:"POST",body:JSON.stringify({schemaVersion:1,kind:"seo",name,environments:[{name:"production",baseUrl:url}]})});setProject(nextProject);const environment=nextProject.environments[0];const audit=await api<SeoResult>("/api/v1/seo/audits",{method:"POST",body:JSON.stringify({schemaVersion:1,kind:"seo",seoProjectId:nextProject.id,environmentId:environment.id,options:{lighthouse:true}})});setResult(audit);const item={at:new Date().toISOString(),score:audit.healthScore??0,findings:audit.findings.length,url:audit.url};const next=[item,...history].slice(0,20);setHistory(next);localStorage.setItem("seo-audit-history",JSON.stringify(next));notify("SEO audit completed");}catch(error){notify(error instanceof Error?error.message:String(error),"error");}finally{setBusy(false)}}
  async function runCrawl(){if(!project)return;setCrawlBusy(true);try{const environment=project.environments[0];const data=await api<CrawlResult>("/api/v1/seo/crawls",{method:"POST",body:JSON.stringify({schemaVersion:1,seoProjectId:project.id,environmentId:environment.id,options:{maxPages:25,maxDepth:3}})});setCrawl(data);notify("Site crawl completed");}catch(error){notify(error instanceof Error?error.message:String(error),"error");}finally{setCrawlBusy(false)}}
  const score=result?.healthScore??0; const severe=result?.findings.filter(item=>item.severity==="high"||item.severity==="critical").length??0;
  return <main className="seo-hub"><header className="seo-hero"><div><span className="eyebrow">UNIFIED SEO WORKSPACE</span><h1>SEO Command Center</h1><p>Audit, crawl, prioritize and monitor one site from a single workspace.</p></div><div className="seo-health"><span>Site health</span><strong>{result?score:"—"}</strong><small>{result?`${result.findings.length} findings · ${severe} urgent`:"Run your first audit"}</small></div></header>
    <section className="seo-project-bar"><form onSubmit={submit}><label>Project<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="seo-url">Website URL<input type="url" required placeholder="https://example.com" value={url} onChange={e=>setUrl(e.target.value)}/></label><button disabled={busy}>{busy?"Auditing…":"Run full audit"}</button></form>{project&&<div className="seo-context"><i/><span>{project.name}</span><code>{project.environments[0].baseUrl}</code><em>Production</em></div>}</section>
    <nav className="seo-tabs" aria-label="SEO tools">{tabs.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><b>{icon}</b><span>{label}</span>{id==="crawler"&&crawl?<small>{crawl.records.length}</small>:null}</button>)}</nav>
    {tab==="overview"&&<section className="seo-dashboard"><div className="seo-kpis"><article><span>Health score</span><strong>{result?score:"—"}<small>/100</small></strong></article><article><span>Technical findings</span><strong>{(grouped.technical?.length??0)+(grouped.indexability?.length??0)}</strong></article><article><span>Content signals</span><strong>{(grouped.metadata?.length??0)+(grouped.content?.length??0)}</strong></article><article><span>Crawled pages</span><strong>{crawl?.records.length??0}</strong></article></div><div className="seo-grid"><article className="seo-panel"><header><div><h2>Priority actions</h2><p>Highest-impact work across all SEO systems</p></div></header><FindingList findings={result?.findings??[]}/></article><article className="seo-panel seo-system-map"><header><div><h2>Workspace coverage</h2><p>Everything connected to this SEO project</p></div></header>{tabs.slice(1).map(([id,label])=><button key={id} onClick={()=>setTab(id)}><span>{label}</span><strong>{id==="crawler"?(crawl?"Ready":"Not run"):result?"Analyzed":"Waiting"}</strong></button>)}</article></div></section>}
    {tab==="technical"&&<ToolPanel title="Technical SEO & Indexability" subtitle="Metadata, canonicalization, crawl directives, structured data and JavaScript rendering"><div className="seo-category-grid">{["technical","indexability","metadata","structuredData","social"].map(category=><article key={category}><header><h3>{category}</h3><strong>{grouped[category]?.length??0}</strong></header><FindingList findings={grouped[category]??[]}/></article>)}</div></ToolPanel>}
    {tab==="content"&&<ToolPanel title="Content & Entity Intelligence" subtitle="Page titles, descriptions, semantic coverage and entity readiness"><FindingList findings={[...(grouped.content??[]),...(grouped.metadata??[]),...(grouped.social??[])]}/></ToolPanel>}
    {tab==="crawler"&&<ToolPanel title="Controlled Site Crawler" subtitle="Robots-aware discovery with SSRF protection and strict resource budgets"><button className="seo-run-tool" disabled={!project||crawlBusy} onClick={runCrawl}>{crawlBusy?"Crawling up to 25 pages…":"Start controlled crawl"}</button>{crawl&&<><div className="seo-kpis compact"><article><span>Pages</span><strong>{crawl.records.length}</strong></article><article><span>Site issues</span><strong>{crawl.issues.length}</strong></article><article><span>Status</span><strong>{crawl.status}</strong></article></div><div className="seo-crawl-table"><table><thead><tr><th>Page</th><th>Status</th><th>Depth</th><th>Indexable</th><th>Issues</th></tr></thead><tbody>{crawl.records.map(row=><tr key={row.url}><td><a href={row.url} target="_blank" rel="noreferrer">{row.title||row.url}</a></td><td>{row.status}</td><td>{row.depth}</td><td>{row.indexable?"Yes":"No"}</td><td>{row.issueCount}</td></tr>)}</tbody></table></div></>}</ToolPanel>}
    {tab==="strategy"&&<ToolPanel title="Keywords, Topics & Campaigns" subtitle="Turn audit evidence into a prioritized SEO delivery plan"><div className="seo-strategy"><article><span>Immediate</span><strong>Resolve {severe} high-impact findings</strong><p>Technical blockers and indexability risks come first.</p></article><article><span>Next</span><strong>Improve metadata coverage</strong><p>{grouped.metadata?.length??0} metadata opportunities detected.</p></article><article><span>Ongoing</span><strong>Build topic and entity authority</strong><p>Use crawl coverage and monitoring trends as campaign evidence.</p></article></div></ToolPanel>}
    {tab==="monitoring"&&<ToolPanel title="Monitoring, Experiments & Digital Twin" subtitle="Track health over time and compare every audit"><div className="seo-history">{history.map(item=><article key={item.at}><time>{new Date(item.at).toLocaleString()}</time><span>{item.url}</span><strong>{item.score}/100</strong><small>{item.findings} findings</small></article>)}{!history.length&&<p className="seo-empty">Audit history will appear here.</p>}</div></ToolPanel>}
  </main>;
}
function ToolPanel({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="seo-panel seo-tool"><header><div><h2>{title}</h2><p>{subtitle}</p></div></header>{children}</section>}
function FindingList({findings}:{findings:Finding[]}){const sorted=[...findings].sort((a,b)=>({critical:0,high:1,medium:2,low:3}[a.severity]??4)-({critical:0,high:1,medium:2,low:3}[b.severity]??4));return <div className="seo-findings">{sorted.map(finding=><article key={finding.id}><i className={`severity ${finding.severity}`}/><div><strong>{finding.message}</strong><small>{finding.ruleId??"SEO signal"}</small></div><em>{finding.severity}</em></article>)}{!findings.length&&<p className="seo-empty">Run an audit to populate this section.</p>}</div>}
