export interface Migration { version: number; up: string; down: string }
export const MIGRATIONS: Migration[] = [{ version: 1, up: `
CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tenants(id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, email TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships(tenant_id TEXT NOT NULL, user_id TEXT NOT NULL, role TEXT NOT NULL, PRIMARY KEY(tenant_id,user_id));
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, kind TEXT NOT NULL, name TEXT NOT NULL, config_json TEXT NOT NULL, created_at TEXT NOT NULL, deleted_at TEXT);
CREATE INDEX IF NOT EXISTS idx_projects_tenant ON projects(tenant_id,id);
CREATE TABLE IF NOT EXISTS environments(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, name TEXT NOT NULL, base_url TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS repository_links(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, code_project_id TEXT NOT NULL, seo_project_id TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL, idempotency_key TEXT NOT NULL, command_json TEXT NOT NULL, config_snapshot_json TEXT NOT NULL, analyzer_versions_json TEXT, lease_owner TEXT, lease_expires_at TEXT, cancel_requested_at TEXT, checkpoint_json TEXT, artifact_id TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, completed_at TEXT, UNIQUE(tenant_id,idempotency_key));
CREATE INDEX IF NOT EXISTS idx_jobs_queue ON jobs(tenant_id,status,created_at);
CREATE TABLE IF NOT EXISTS job_attempts(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, job_id TEXT NOT NULL, attempt_no INTEGER NOT NULL, status TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT, error TEXT, UNIQUE(job_id,attempt_no));
CREATE TABLE IF NOT EXISTS job_steps(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, job_id TEXT NOT NULL, attempt_id TEXT NOT NULL, name TEXT NOT NULL, status TEXT NOT NULL, checkpoint_json TEXT, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS job_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, tenant_id TEXT NOT NULL, job_id TEXT NOT NULL, type TEXT NOT NULL, payload_json TEXT NOT NULL, occurred_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_events_job ON job_events(tenant_id,job_id,sequence);
CREATE TABLE IF NOT EXISTS artifacts(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, sha256 TEXT NOT NULL, size_bytes INTEGER NOT NULL, media_type TEXT NOT NULL, storage_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL, retain_until TEXT, legal_hold INTEGER NOT NULL DEFAULT 0, deleted_at TEXT);
CREATE TABLE IF NOT EXISTS findings(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, job_id TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS suppressions(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS baselines(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, artifact_id TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS quality_gates(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, job_id TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS proposals(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, job_id TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS approvals(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, proposal_id TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS patches(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, proposal_id TEXT NOT NULL, artifact_id TEXT, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS verification_runs(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, patch_id TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS connector_accounts(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, provider TEXT NOT NULL, secret_ref TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sync_runs(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, connector_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, payload_json TEXT NOT NULL, UNIQUE(tenant_id,idempotency_key));
CREATE TABLE IF NOT EXISTS retention_policies(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT, days INTEGER NOT NULL, legal_hold INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS deletion_requests(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, project_id TEXT NOT NULL, status TEXT NOT NULL, requested_at TEXT NOT NULL, completed_at TEXT, verification_json TEXT);
CREATE TABLE IF NOT EXISTS outbox(id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, aggregate_id TEXT NOT NULL, type TEXT NOT NULL, payload_json TEXT NOT NULL, created_at TEXT NOT NULL, published_at TEXT);
`, down: `DROP TABLE IF EXISTS outbox; DROP TABLE IF EXISTS deletion_requests; DROP TABLE IF EXISTS retention_policies; DROP TABLE IF EXISTS sync_runs; DROP TABLE IF EXISTS connector_accounts; DROP TABLE IF EXISTS verification_runs; DROP TABLE IF EXISTS patches; DROP TABLE IF EXISTS approvals; DROP TABLE IF EXISTS proposals; DROP TABLE IF EXISTS quality_gates; DROP TABLE IF EXISTS baselines; DROP TABLE IF EXISTS suppressions; DROP TABLE IF EXISTS findings; DROP TABLE IF EXISTS artifacts; DROP TABLE IF EXISTS job_events; DROP TABLE IF EXISTS job_steps; DROP TABLE IF EXISTS job_attempts; DROP TABLE IF EXISTS jobs; DROP TABLE IF EXISTS repository_links; DROP TABLE IF EXISTS environments; DROP TABLE IF EXISTS projects; DROP TABLE IF EXISTS memberships; DROP TABLE IF EXISTS users; DROP TABLE IF EXISTS tenants; DROP TABLE IF EXISTS schema_migrations;` }, { version: 2, up: `ALTER TABLE jobs ADD COLUMN result_json TEXT;`, down: `ALTER TABLE jobs DROP COLUMN result_json;` }];

export async function migrate(database: import("./port").PersistencePort, target = MIGRATIONS.length): Promise<void> { const applied = await database.query<{ version: number }>("SELECT version FROM schema_migrations ORDER BY version").catch(() => []); const versions = new Set(applied.map((row) => Number(row.version))); for (const migration of MIGRATIONS) if (migration.version <= target && !versions.has(migration.version)) await database.transaction(async (tx) => { await tx.execute(migration.up); await tx.execute("INSERT INTO schema_migrations(version,applied_at) VALUES(?,?)", [migration.version, new Date().toISOString()]); }); }
export async function rollback(database: import("./port").PersistencePort, target = 0): Promise<void> { const applied = await database.query<{ version: number }>("SELECT version FROM schema_migrations ORDER BY version DESC"); for (const row of applied) { const migration = MIGRATIONS.find((item) => item.version === Number(row.version)); if (migration && migration.version > target) await database.transaction(async (tx) => { await tx.execute("DELETE FROM schema_migrations WHERE version=?", [migration.version]); await tx.execute(migration.down); }); } }
