import { randomUUID } from "node:crypto";
import type { AuditCommand, JobEvent, Project } from "../../contracts";
import { JobEventSchema, ProjectSchema } from "../../contracts";
import type { PersistencePort } from "./port";

export type DurableJobStatus = "queued" | "leased" | "running" | "retry_wait" | "completed" | "failed" | "cancelled";
export interface DurableJob { id: string; tenantId: string; projectId: string; kind: AuditCommand["kind"]; status: DurableJobStatus; idempotencyKey: string; command: AuditCommand; configSnapshot: Record<string, unknown>; analyzerVersions?: Record<string, string>; leaseOwner?: string; leaseExpiresAt?: string; cancelRequestedAt?: string; checkpoint?: Record<string, unknown>; artifactId?: string; createdAt: string; updatedAt: string; completedAt?: string }
const parse = <T>(value: unknown): T => JSON.parse(String(value)) as T;
const SECRET_KEY = /(?:api[_-]?key|access[_-]?token|authorization|password|secret|session[_-]?id)/i;
export function sanitizePersistentSnapshot(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sanitizePersistentSnapshot);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, SECRET_KEY.test(key) ? "<REDACTED>" : sanitizePersistentSnapshot(item)]));
  return value;
}

export class PersistentProjectRepository {
  constructor(private readonly database: PersistencePort) {}
  async save(tenantId: string, project: Project, privateConfig: Record<string, unknown> = {}) { ProjectSchema.parse(project); await this.database.execute("INSERT INTO projects(id,tenant_id,kind,name,config_json,created_at) VALUES(?,?,?,?,?,?)", [project.id, tenantId, project.kind, project.name, JSON.stringify({ ...privateConfig, ...(project.kind === "seo" ? { environments: project.environments } : {}) }), new Date().toISOString()]); }
  async get(tenantId: string, id: string): Promise<{ public: Project; privateConfig: Record<string, unknown> } | undefined> { const rows = await this.database.query<Record<string, unknown>>("SELECT * FROM projects WHERE tenant_id=? AND id=? AND deleted_at IS NULL", [tenantId, id]); const row = rows[0]; if (!row) return undefined; const config = parse<Record<string, unknown>>(row.config_json); const value = row.kind === "code" ? { schemaVersion: 1, kind: "code", id: row.id, name: row.name } : { schemaVersion: 1, kind: "seo", id: row.id, name: row.name, environments: config.environments ?? [] }; return { public: ProjectSchema.parse(value) as Project, privateConfig: config }; }
  async list(tenantId: string): Promise<Project[]> { const rows = await this.database.query<{ id: string }>("SELECT id FROM projects WHERE tenant_id=? AND deleted_at IS NULL ORDER BY created_at", [tenantId]); return (await Promise.all(rows.map((row) => this.get(tenantId, row.id)))).flatMap((item) => item ? [item.public] : []); }
  async markDeleted(tenantId: string, id: string, at = new Date().toISOString()) { return (await this.database.execute("UPDATE projects SET deleted_at=? WHERE tenant_id=? AND id=? AND deleted_at IS NULL", [at, tenantId, id])).changes > 0; }
}

export class PersistentJobRepository {
  constructor(private readonly database: PersistencePort) {}
  private map(row: Record<string, unknown>): DurableJob { return { id: String(row.id), tenantId: String(row.tenant_id), projectId: String(row.project_id), kind: row.kind as DurableJob["kind"], status: row.status as DurableJobStatus, idempotencyKey: String(row.idempotency_key), command: parse<AuditCommand>(row.command_json), configSnapshot: parse<Record<string, unknown>>(row.config_snapshot_json), analyzerVersions: row.analyzer_versions_json ? parse<Record<string, string>>(row.analyzer_versions_json) : undefined, leaseOwner: row.lease_owner ? String(row.lease_owner) : undefined, leaseExpiresAt: row.lease_expires_at ? String(row.lease_expires_at) : undefined, cancelRequestedAt: row.cancel_requested_at ? String(row.cancel_requested_at) : undefined, checkpoint: row.checkpoint_json ? parse<Record<string, unknown>>(row.checkpoint_json) : undefined, artifactId: row.artifact_id ? String(row.artifact_id) : undefined, createdAt: String(row.created_at), updatedAt: String(row.updated_at), completedAt: row.completed_at ? String(row.completed_at) : undefined }; }
  async create(input: { tenantId: string; projectId: string; idempotencyKey: string; command: AuditCommand; configSnapshot?: Record<string, unknown> }): Promise<{ job: DurableJob; duplicate: boolean }> { const existing = await this.byIdempotency(input.tenantId, input.idempotencyKey); if (existing) return { job: existing, duplicate: true }; const now = new Date().toISOString(); const id = randomUUID(); try { await this.database.transaction(async (tx) => { await tx.execute("INSERT INTO jobs(id,tenant_id,project_id,kind,status,idempotency_key,command_json,config_snapshot_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)", [id, input.tenantId, input.projectId, input.command.kind, "queued", input.idempotencyKey, JSON.stringify(input.command), JSON.stringify(input.configSnapshot ?? {}), now, now]); await tx.execute("INSERT INTO job_events(id,tenant_id,job_id,type,payload_json,occurred_at) VALUES(?,?,?,?,?,?)", [randomUUID(), input.tenantId, id, "job.queued", "{}", now]); await tx.execute("INSERT INTO outbox(id,tenant_id,aggregate_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)", [randomUUID(), input.tenantId, id, "job.queued", JSON.stringify({ jobId: id }), now]); }); } catch (error) { const duplicate = await this.byIdempotency(input.tenantId, input.idempotencyKey); if (duplicate) return { job: duplicate, duplicate: true }; throw error; } return { job: (await this.get(input.tenantId, id))!, duplicate: false }; }
  async get(tenantId: string, id: string) { const rows = await this.database.query<Record<string, unknown>>("SELECT * FROM jobs WHERE tenant_id=? AND id=?", [tenantId, id]); return rows[0] ? this.map(rows[0]) : undefined; }
  async list(tenantId: string) { return (await this.database.query<Record<string, unknown>>("SELECT * FROM jobs WHERE tenant_id=? ORDER BY created_at DESC", [tenantId])).map((row) => this.map(row)); }
  async byIdempotency(tenantId: string, key: string) { const rows = await this.database.query<Record<string, unknown>>("SELECT * FROM jobs WHERE tenant_id=? AND idempotency_key=?", [tenantId, key]); return rows[0] ? this.map(rows[0]) : undefined; }
  async appendEvent(event: JobEvent) { JobEventSchema.parse(event); const job = await this.database.query<{ tenant_id: string }>("SELECT tenant_id FROM jobs WHERE id=?", [event.jobId]); if (!job[0]) throw new Error("Job not found"); const id = `${event.jobId}:${event.type}:${event.occurredAt}`; try { await this.database.execute("INSERT INTO job_events(id,tenant_id,job_id,type,payload_json,occurred_at) VALUES(?,?,?,?,?,?)", [id, job[0].tenant_id, event.jobId, event.type, JSON.stringify(event.payload), event.occurredAt]); } catch (error) { const duplicate = await this.database.query<{ id: string }>("SELECT id FROM job_events WHERE id=?", [id]); if (!duplicate[0]) throw error; } }
  async events(tenantId: string, jobId: string) { return this.database.query<Record<string, unknown>>("SELECT * FROM job_events WHERE tenant_id=? AND job_id=? ORDER BY sequence", [tenantId, jobId]); }
  async requestCancellation(tenantId: string, id: string) { const now = new Date().toISOString(); return (await this.database.execute("UPDATE jobs SET cancel_requested_at=?,updated_at=? WHERE tenant_id=? AND id=? AND status NOT IN ('completed','failed','cancelled')", [now, now, tenantId, id])).changes > 0; }
  async saveCheckpoint(tenantId: string, id: string, checkpoint: Record<string, unknown>) { return (await this.database.execute("UPDATE jobs SET checkpoint_json=?,updated_at=? WHERE tenant_id=? AND id=? AND status NOT IN ('completed','failed','cancelled')", [JSON.stringify(checkpoint), new Date().toISOString(), tenantId, id])).changes > 0; }
  async complete(tenantId: string, id: string, artifactId: string | undefined, analyzerVersions: Record<string, string>) { const now = new Date().toISOString(); return (await this.database.execute("UPDATE jobs SET status='completed',artifact_id=?,analyzer_versions_json=?,lease_owner=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE tenant_id=? AND id=? AND status IN ('leased','running')", [artifactId ?? null, JSON.stringify(analyzerVersions), now, now, tenantId, id])).changes > 0; }
  async markRunning(tenantId: string, id: string, workerId = `process-${process.pid}`, leaseMs = 30_000) { const now = new Date(); return (await this.database.execute("UPDATE jobs SET status='running',lease_owner=?,lease_expires_at=?,updated_at=? WHERE tenant_id=? AND id=? AND status IN ('queued','leased','retry_wait')", [workerId, new Date(now.getTime()+leaseMs).toISOString(), now.toISOString(), tenantId, id])).changes > 0; }
  async finish(tenantId: string, id: string, status: "completed" | "failed" | "cancelled", checkpoint?: Record<string, unknown>) { const now = new Date().toISOString(); return (await this.database.execute("UPDATE jobs SET status=?,checkpoint_json=?,lease_owner=NULL,lease_expires_at=NULL,completed_at=?,updated_at=? WHERE tenant_id=? AND id=? AND status NOT IN ('completed','failed','cancelled')", [status, checkpoint ? JSON.stringify(checkpoint) : null, now, now, tenantId, id])).changes > 0; }
}
