import fs from "node:fs/promises";
import path from "node:path";
import { createHash, randomUUID } from "node:crypto";
import { redactSecrets } from "../core/trustSecurity";
import type { SeoBusinessType, SeoProfileInput } from "./projectProfile";
export type MemoryKind = "fact" | "assumption" | "decision" | "open-question";
export interface SeoMemoryItem { id: string; kind: MemoryKind; field: string; value: unknown; source: "user" | "system" | "inference"; confidence: number; confirmed: boolean; rejected?: boolean; createdAt: string }
export interface OnboardingQuestion { id: string; field: string; prompt: { en: string; fa: string }; why: { en: string; fa: string }; required: boolean; options?: string[] }
export interface SeoOnboardingSession { version: 1; id: string; projectId: string; campaignId: string; language: "en" | "fa"; status: "active" | "review" | "completed"; memory: SeoMemoryItem[]; skipped: string[]; contradictions: Array<{ field: string; values: unknown[] }>; createdAt: string; updatedAt: string }
const questions: OnboardingQuestion[] = [
  { id: "business", field: "businessType", prompt: { en: "What type of site is this?", fa: "نوع این وب‌سایت چیست؟" }, why: { en: "It selects relevant technical and schema defaults.", fa: "برای انتخاب قواعد فنی و Schema مناسب لازم است." }, required: true, options: ["saas","ecommerce","marketplace","local","publisher","documentation","multilingual","programmatic"] },
  { id: "goals", field: "goals", prompt: { en: "What SEO outcomes matter most?", fa: "مهم‌ترین هدف‌های SEO چیست؟" }, why: { en: "Goals determine prioritization; they do not guarantee rankings.", fa: "هدف‌ها اولویت‌بندی را تعیین می‌کنند و تضمین رتبه نیستند." }, required: true },
  { id: "markets", field: "markets", prompt: { en: "Which markets and languages are in scope?", fa: "کدام بازارها و زبان‌ها در محدوده‌اند؟" }, why: { en: "Needed for hreflang, locale and content checks.", fa: "برای بررسی hreflang، زبان و محتوا لازم است." }, required: true },
  { id: "audiences", field: "audiences", prompt: { en: "Who are the priority audiences?", fa: "مخاطبان اصلی چه کسانی هستند؟" }, why: { en: "Audience needs shape content and intent analysis.", fa: "نیاز مخاطب تحلیل محتوا و intent را شکل می‌دهد." }, required: false },
  { id: "conversions", field: "conversions", prompt: { en: "Which conversions should SEO support?", fa: "SEO باید از کدام تبدیل‌ها پشتیبانی کند؟" }, why: { en: "Connects recommendations to measurable business outcomes.", fa: "پیشنهادها را به خروجی قابل‌اندازه‌گیری کسب‌وکار متصل می‌کند." }, required: false },
  { id: "pages", field: "priorityPages", prompt: { en: "Which pages or templates are highest priority?", fa: "کدام صفحه‌ها یا قالب‌ها اولویت بیشتری دارند؟" }, why: { en: "Keeps crawling and recommendations bounded.", fa: "خزش و پیشنهادها را محدود و هدفمند نگه می‌دارد." }, required: false },
  { id: "competitors", field: "competitors", prompt: { en: "Which competitors should be used only as references?", fa: "کدام رقبا فقط به‌عنوان مرجع بررسی شوند؟" }, why: { en: "Provides comparison context without inventing market facts.", fa: "زمینه مقایسه می‌دهد بدون ساختن ادعای بازاری." }, required: false },
  { id: "resources", field: "resources", prompt: { en: "What engineering and content resources are available?", fa: "چه منابع فنی و محتوایی در دسترس است؟" }, why: { en: "Prevents impractical plans.", fa: "از برنامه‌های غیرعملی جلوگیری می‌کند." }, required: false },
  { id: "approval", field: "approvalConstraints", prompt: { en: "Which changes require additional approval?", fa: "کدام تغییرها نیاز به تأیید اضافه دارند؟" }, why: { en: "Preserves human review boundaries.", fa: "مرزهای بازبینی انسانی را حفظ می‌کند." }, required: true },
];
const clean = (value: unknown): unknown => typeof value === "string" ? redactSecrets(value).slice(0, 10_000) : Array.isArray(value) ? value.map(clean) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).map(([key, item]) => [key, clean(item)])) : value;
export function nextOnboardingQuestion(session: SeoOnboardingSession): OnboardingQuestion | undefined { const answered = new Set(session.memory.filter((item) => !item.rejected).map((item) => item.field)); return questions.find((question) => !answered.has(question.field) && !session.skipped.includes(question.field)); }
export function answerOnboarding(session: SeoOnboardingSession, field: string, value: unknown, options: { kind?: MemoryKind; source?: SeoMemoryItem["source"]; confidence?: number; confirmed?: boolean } = {}): SeoOnboardingSession { const sanitized = clean(value); const existing = session.memory.filter((item) => item.field === field && item.confirmed && !item.rejected); const contradiction = existing.some((item) => JSON.stringify(item.value) !== JSON.stringify(sanitized)); const memory = [...session.memory, { id: randomUUID(), kind: options.kind ?? (options.source === "inference" ? "assumption" : "fact"), field, value: sanitized, source: options.source ?? "user", confidence: Math.max(0, Math.min(1, options.confidence ?? (options.source === "inference" ? .5 : 1))), confirmed: options.confirmed ?? options.source !== "inference", createdAt: new Date().toISOString() } satisfies SeoMemoryItem]; return { ...session, memory, contradictions: contradiction ? [...session.contradictions.filter((item) => item.field !== field), { field, values: [...existing.map((item) => item.value), sanitized] }] : session.contradictions, updatedAt: new Date().toISOString() }; }
export function skipOnboardingQuestion(session: SeoOnboardingSession, field: string) { return { ...session, skipped: [...new Set([...session.skipped, field])], updatedAt: new Date().toISOString() }; }
export function resolveContradiction(session: SeoOnboardingSession, field: string, acceptedMemoryId: string) { return { ...session, memory: session.memory.map((item) => item.field === field ? { ...item, confirmed: item.id === acceptedMemoryId, rejected: item.id !== acceptedMemoryId } : item), contradictions: session.contradictions.filter((item) => item.field !== field), updatedAt: new Date().toISOString() }; }
export function updateMemoryItem(session: SeoOnboardingSession, memoryId: string, value: unknown) { let found = false; const memory = session.memory.map((item) => { if (item.id !== memoryId) return item; found = true; return { ...item, value: clean(value), confirmed: true, rejected: false }; }); if (!found) throw new Error("Memory item not found"); return { ...session, memory, updatedAt: new Date().toISOString() }; }
export function rejectMemoryItem(session: SeoOnboardingSession, memoryId: string) { let found = false; const memory = session.memory.map((item) => { if (item.id !== memoryId) return item; found = true; return { ...item, confirmed: false, rejected: true }; }); if (!found) throw new Error("Memory item not found"); const field = memory.find((item) => item.id === memoryId)!.field; return { ...session, memory, contradictions: session.contradictions.filter((item) => item.field !== field), updatedAt: new Date().toISOString() }; }
export function buildProjectBrief(session: SeoOnboardingSession) { const values: Record<string, unknown> = {}; for (const item of session.memory.filter((entry) => entry.confirmed && !entry.rejected)) values[item.field] = item.value; const openQuestions = questions.filter((question) => question.required && values[question.field] === undefined && !session.skipped.includes(question.field)); const profile: SeoProfileInput = { businessType: (values.businessType as SeoBusinessType | undefined) ?? "saas", markets: Array.isArray(values.markets) ? values.markets as string[] : [], audiences: Array.isArray(values.audiences) ? values.audiences as string[] : [], conversions: Array.isArray(values.conversions) ? values.conversions as string[] : [], competitors: Array.isArray(values.competitors) ? values.competitors as string[] : [] }; return { projectId: session.projectId, campaignId: session.campaignId, facts: session.memory.filter((item) => item.kind === "fact" && item.confirmed && !item.rejected), assumptions: session.memory.filter((item) => item.kind === "assumption" && !item.rejected), decisions: session.memory.filter((item) => item.kind === "decision" && !item.rejected), openQuestions, contradictions: session.contradictions, proposedProfile: profile, readyToConfirm: openQuestions.length === 0 && session.contradictions.length === 0 }; }
export function reviewOnboarding(session: SeoOnboardingSession) { return { ...session, status: "review" as const, updatedAt: new Date().toISOString() }; }
export function completeOnboarding(session: SeoOnboardingSession) { const brief = buildProjectBrief(session); if (!brief.readyToConfirm) throw new Error("Onboarding has unresolved required questions or contradictions"); return { ...session, status: "completed" as const, updatedAt: new Date().toISOString() }; }
export class SeoOnboardingStore { constructor(private readonly root: string) {} private file(projectId: string, campaignId: string) { const key = createHash("sha256").update(`${projectId}\0${campaignId}`).digest("hex"); return path.join(this.root, key, "onboarding.json"); } async create(projectId: string, campaignId = "default", language: "en" | "fa" = "fa") { const now = new Date().toISOString(); const session: SeoOnboardingSession = { version: 1, id: randomUUID(), projectId, campaignId, language, status: "active", memory: [], skipped: [], contradictions: [], createdAt: now, updatedAt: now }; await this.save(session); return session; } async save(session: SeoOnboardingSession) { const file = this.file(session.projectId, session.campaignId); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, JSON.stringify(session, null, 2)); } async get(projectId: string, campaignId = "default") { return JSON.parse(await fs.readFile(this.file(projectId, campaignId), "utf8")) as SeoOnboardingSession; } async reset(projectId: string, campaignId = "default") { await fs.rm(path.dirname(this.file(projectId, campaignId)), { recursive: true, force: true }); } async export(projectId: string, campaignId = "default") { return JSON.stringify(await this.get(projectId, campaignId), null, 2); } }
export { questions as ONBOARDING_QUESTIONS };
