import fs from "node:fs/promises";
import path from "node:path";
import { createHash } from "node:crypto";
import { redactSecrets } from "../core/trustSecurity";
import { InMemorySecretStore, type SecretStore } from "../platform/security/secrets";

export const SEO_PROFILE_VERSION = 1;
export type SeoBusinessType = "saas" | "ecommerce" | "marketplace" | "local" | "publisher" | "documentation" | "multilingual" | "programmatic";
export interface SeoRules { crawl: { maxPages: number; maxDepth: number; include: string[]; exclude: string[]; includeSubdomains: boolean }; indexabilityExceptions: string[]; templateRules: Record<string, { pattern: string; requiredHeadings?: number; minWords?: number }>; schemaRequirements: Record<string, string[]>; performanceBudgets: { lcpMs: number; cls: number; tbtMs: number } }
export interface SeoProjectProfile { version: 1; id: string; name: string; businessType: SeoBusinessType; brand: { name: string; aliases: string[] }; domains: string[]; environments: Record<string, string>; markets: string[]; languages: string[]; audiences: string[]; conversions: string[]; competitors: string[]; rules: SeoRules; updatedAt: string }
export type SeoProfileInput = Partial<Omit<SeoProjectProfile, "version" | "id" | "updatedAt" | "rules">> & { rules?: Partial<SeoRules> };
export interface ResolvedSeoConfig { value: Record<string, unknown>; provenance: Record<string, "global" | "project" | "campaign" | "run"> }

const baseRules: SeoRules = { crawl: { maxPages: 100, maxDepth: 4, include: [], exclude: ["/logout", "/admin"], includeSubdomains: false }, indexabilityExceptions: [], templateRules: {}, schemaRequirements: {}, performanceBudgets: { lcpMs: 2500, cls: .1, tbtMs: 200 } };
export const SEO_PRESETS: Record<SeoBusinessType, SeoProfileInput> = {
  saas: { businessType: "saas", rules: { ...baseRules, schemaRequirements: { homepage: ["Organization", "WebSite"], product: ["SoftwareApplication"] } } },
  ecommerce: { businessType: "ecommerce", rules: { ...baseRules, schemaRequirements: { product: ["Product", "BreadcrumbList"], category: ["BreadcrumbList"] } } },
  marketplace: { businessType: "marketplace", rules: { ...baseRules, crawl: { ...baseRules.crawl, maxPages: 500 } } },
  local: { businessType: "local", rules: { ...baseRules, schemaRequirements: { location: ["LocalBusiness"] } } },
  publisher: { businessType: "publisher", rules: { ...baseRules, schemaRequirements: { article: ["Article", "BreadcrumbList"] } } },
  documentation: { businessType: "documentation", rules: { ...baseRules, schemaRequirements: { documentation: ["TechArticle", "BreadcrumbList"] } } },
  multilingual: { businessType: "multilingual", rules: { ...baseRules, schemaRequirements: { page: ["WebPage"] } } },
  programmatic: { businessType: "programmatic", rules: { ...baseRules, crawl: { ...baseRules.crawl, maxPages: 1000, maxDepth: 6 } } },
};

function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T; }
function deepMerge(target: Record<string, unknown>, source: Record<string, unknown>, layer: ResolvedSeoConfig["provenance"][string], prefix: string, provenance: ResolvedSeoConfig["provenance"]) { for (const [key, value] of Object.entries(source)) { if (value === undefined) continue; const dotted = prefix ? `${prefix}.${key}` : key; if (value && typeof value === "object" && !Array.isArray(value)) { const current = target[key]; if (!current || typeof current !== "object" || Array.isArray(current)) target[key] = {}; deepMerge(target[key] as Record<string, unknown>, value as Record<string, unknown>, layer, dotted, provenance); } else { target[key] = clone(value); provenance[dotted] = layer; } } }
export function resolveSeoConfig(global: Record<string, unknown>, project: Record<string, unknown>, campaign: Record<string, unknown> = {}, run: Record<string, unknown> = {}): ResolvedSeoConfig { const value: Record<string, unknown> = {}; const provenance: ResolvedSeoConfig["provenance"] = {}; for (const [layer, input] of [["global", global], ["project", project], ["campaign", campaign], ["run", run]] as const) deepMerge(value, input, layer, "", provenance); return { value, provenance }; }
export function validateSeoProfile(profile: SeoProjectProfile): string[] { const errors: string[] = []; if (!profile.name.trim()) errors.push("name is required"); if (!SEO_PRESETS[profile.businessType]) errors.push("businessType is invalid"); if (!profile.domains.length) errors.push("at least one domain is required"); for (const domain of profile.domains) try { const url = new URL(domain); if (!["http:", "https:"].includes(url.protocol)) errors.push(`unsupported domain protocol: ${domain}`); } catch { errors.push(`invalid domain: ${domain}`); } for (const language of profile.languages) if (!/^[a-z]{2,3}(?:-[A-Z]{2})?$/.test(language)) errors.push(`invalid language: ${language}`); if (profile.rules.crawl.maxPages < 1 || profile.rules.crawl.maxPages > 10000) errors.push("crawl.maxPages must be 1..10000"); return errors; }

export class SeoProfileStore {
  private projectDir(projectId: string) { if (!/^[a-zA-Z0-9_-]{3,80}$/.test(projectId)) throw new Error("Invalid project ID"); return path.join(this.root, createHash("sha256").update(projectId).digest("hex").slice(0, 24)); }
  constructor(private readonly root: string, private readonly secrets: SecretStore = new InMemorySecretStore()) {}
  async create(projectId: string, input: SeoProfileInput): Promise<SeoProjectProfile> { const preset = SEO_PRESETS[input.businessType ?? "saas"]; const merged = resolveSeoConfig(preset as Record<string, unknown>, input as Record<string, unknown>).value as unknown as SeoProfileInput; const profile: SeoProjectProfile = { version: 1, id: projectId, name: merged.name ?? projectId, businessType: merged.businessType ?? "saas", brand: merged.brand ?? { name: merged.name ?? projectId, aliases: [] }, domains: merged.domains ?? [], environments: merged.environments ?? {}, markets: merged.markets ?? [], languages: merged.languages ?? ["en"], audiences: merged.audiences ?? [], conversions: merged.conversions ?? [], competitors: merged.competitors ?? [], rules: { ...clone(baseRules), ...(merged.rules ?? {}), crawl: { ...clone(baseRules.crawl), ...(merged.rules?.crawl ?? {}) }, performanceBudgets: { ...clone(baseRules.performanceBudgets), ...(merged.rules?.performanceBudgets ?? {}) } }, updatedAt: new Date().toISOString() }; const errors = validateSeoProfile(profile); if (errors.length) throw new Error(errors.join("; ")); await this.saveVersion(profile); return profile; }
  private async saveVersion(profile: SeoProjectProfile) { const dir = this.projectDir(profile.id); const versions = path.join(dir, "versions"); await fs.mkdir(versions, { recursive: true }); const stamp = `${Date.now()}-${createHash("sha256").update(JSON.stringify(profile)).digest("hex").slice(0, 8)}`; await fs.writeFile(path.join(versions, `${stamp}.json`), JSON.stringify(profile, null, 2)); const temp = path.join(dir, "profile.tmp"); await fs.writeFile(temp, JSON.stringify(profile, null, 2)); await fs.rename(temp, path.join(dir, "profile.json")); }
  async get(projectId: string) { return JSON.parse(await fs.readFile(path.join(this.projectDir(projectId), "profile.json"), "utf8")) as SeoProjectProfile; }
  async update(projectId: string, input: SeoProfileInput) { const current = await this.get(projectId); const next = resolveSeoConfig(current as unknown as Record<string, unknown>, input as Record<string, unknown>).value as unknown as SeoProjectProfile; next.version = 1; next.id = projectId; next.updatedAt = new Date().toISOString(); const errors = validateSeoProfile(next); if (errors.length) throw new Error(errors.join("; ")); await this.saveVersion(next); return next; }
  async history(projectId: string) { const dir = path.join(this.projectDir(projectId), "versions"); return (await fs.readdir(dir)).filter((name) => /^\d+-[a-f0-9]{8}\.json$/.test(name)).sort().reverse(); }
  async rollback(projectId: string, version: string) { if (!/^\d+-[a-f0-9]{8}\.json$/.test(version)) throw new Error("Invalid version"); const profile = JSON.parse(await fs.readFile(path.join(this.projectDir(projectId), "versions", version), "utf8")) as SeoProjectProfile; profile.updatedAt = new Date().toISOString(); await this.saveVersion(profile); return profile; }
  async setCredentials(projectId: string, credentials: Record<string, string>) { const refs: Record<string, string> = {}; for (const [key, value] of Object.entries(credentials)) { if (!/^[A-Z0-9_]{2,80}$/i.test(key)) throw new Error("Invalid credential name"); refs[key] = await this.secrets.put(value); } const dir = this.projectDir(projectId); await fs.mkdir(dir, { recursive: true }); await fs.writeFile(path.join(dir, "credential-refs.json"), JSON.stringify(refs)); }
  async export(projectId: string) { const profile = await this.get(projectId); return JSON.stringify({ exportedAt: new Date().toISOString(), profile: JSON.parse(redactSecrets(JSON.stringify(profile))) }, null, 2); }
  async import(projectId: string, raw: string) { const parsed = JSON.parse(raw) as { profile?: Record<string, unknown> } | Record<string, unknown>; const value = ("profile" in parsed ? parsed.profile ?? {} : parsed) as Record<string, unknown>; const migrated = migrateSeoProfile(value); return this.create(projectId, migrated); }
}
export function migrateSeoProfile(input: Record<string, unknown>): SeoProfileInput { const version = typeof input.version === "number" ? input.version : 0; if (version > SEO_PROFILE_VERSION) throw new Error("Profile version is newer than this application"); if (version === 0) { const legacy = { ...input }; if (typeof legacy.domain === "string" && !legacy.domains) legacy.domains = [legacy.domain]; delete legacy.domain; return legacy as SeoProfileInput; } return input as SeoProfileInput; }
