import { randomUUID } from "node:crypto"; import { redactSecrets } from "../core/trustSecurity";
export type SearchIntent="informational"|"commercial"|"transactional"|"navigational"|"local";
export interface Keyword{term:string;source:string;market:string;language:string;device:"desktop"|"mobile"|"all";collectedAt:string;topic:string;cluster:string;intent:SearchIntent;funnel:"awareness"|"consideration"|"conversion";targetUrl?:string;campaignIds:string[];branded:boolean;confidence:number;history:Array<{at:string;targetUrl?:string}>}
export function normalizeKeyword(input:Partial<Keyword>&{term:string}):Keyword{return{term:input.term.trim().toLocaleLowerCase(),source:input.source??"manual",market:input.market??"global",language:input.language??"en",device:input.device??"all",collectedAt:input.collectedAt??new Date().toISOString(),topic:input.topic??"unclassified",cluster:input.cluster??"unclassified",intent:input.intent??"informational",funnel:input.funnel??"awareness",targetUrl:input.targetUrl,campaignIds:input.campaignIds??[],branded:input.branded??false,confidence:Math.max(0,Math.min(1,input.confidence??.5)),history:input.history??[]}}
export function mapKeyword(k:Keyword,url:string){return{...k,targetUrl:url,history:[...k.history,{at:new Date().toISOString(),targetUrl:k.targetUrl}]}}
export function keywordConflicts(items:Keyword[]){const findings:string[]=[];for(const k of items)if(!k.targetUrl)findings.push(`Unmapped demand: ${k.term}`);const byTerm=new Map<string,Keyword[]>();items.forEach(k=>byTerm.set(k.term,[...(byTerm.get(k.term)??[]),k]));byTerm.forEach((v,k)=>{if(new Set(v.map(x=>x.targetUrl).filter(Boolean)).size>1)findings.push(`Competing URLs: ${k}`)});const byUrl=new Map<string,Keyword[]>();items.filter(k=>k.targetUrl).forEach(k=>byUrl.set(k.targetUrl!,[...(byUrl.get(k.targetUrl!)??[]),k]));byUrl.forEach((v,u)=>{if(new Set(v.map(x=>x.intent)).size>1)findings.push(`Incompatible intents: ${u}`)});return findings}
export function opportunityScore(x:{businessValue:number;relevance:number;evidence:number;feasibility:number;effort:number}){const factors={businessValue:x.businessValue*.3,relevance:x.relevance*.25,evidence:x.evidence*.2,feasibility:x.feasibility*.15,effort:(100-x.effort)*.1};return{score:Math.round(Object.values(factors).reduce((a,b)=>a+b,0)),factors}}
export type CampaignTemplate="launch"|"category-growth"|"local"|"international"|"migration"|"seasonal"|"authority"|"recovery"|"cwv"|"refresh";
export interface Campaign{id:string;name:string;template:CampaignTemplate;goal:string;start:string;end:string;audiences:string[];markets:string[];topics:string[];targetUrls:string[];competitors:string[];owners:string[];budget:number;dependencies:string[];overrides:Record<string,unknown>;kpis:Array<{name:string;baseline:number;target:number;milestones:number[];stopBelow?:number}>;approvalRoles:string[];status:"draft"|"active"|"paused"|"complete"}
export function createCampaign(input:Omit<Campaign,"id"|"status">):Campaign{return{...input,id:randomUUID(),status:"draft"}};
export function prioritizeForCampaign(items:Array<{id:string;campaignIds?:string[];businessImpact:number;confidence:number;effort:number;risk:number}>,campaignId:string){return items.map(x=>({...x,score:(x.campaignIds?.includes(campaignId)?25:0)+x.businessImpact*.35+x.confidence*.25-x.effort*.1-x.risk*.15})).sort((a,b)=>b.score-a.score)}
export type CopilotMode="discover"|"strategize"|"operate"|"explain"; export type MutationStage="proposal"|"evidence"|"preview"|"approval"|"apply"|"verify";
export interface CopilotSession{id:string;projectId:string;campaignId:string;mode:CopilotMode;facts:string[];assumptions:string[];questions:string[];evidence:string[];memory:string[];stage:MutationStage;budgets:{tokens:number;cost:number;seconds:number;files:number;approvals:number};usage:{tokens:number;cost:number;seconds:number;files:number;approvals:number}}
const stages:MutationStage[]=["proposal","evidence","preview","approval","apply","verify"];
export function createCopilot(projectId:string,campaignId:string,mode:CopilotMode,budgets:CopilotSession["budgets"]):CopilotSession{return{id:randomUUID(),projectId,campaignId,mode,facts:[],assumptions:[],questions:[],evidence:[],memory:[],stage:"proposal",budgets,usage:{tokens:0,cost:0,seconds:0,files:0,approvals:0}}}
export function advanceCopilot(s:CopilotSession,next:MutationStage,usage:Partial<CopilotSession["usage"]>={}){if(stages.indexOf(next)!==stages.indexOf(s.stage)+1)throw new Error("Invalid mutation workflow");const total={...s.usage};for(const k of Object.keys(total) as Array<keyof typeof total>){total[k]+=usage[k]??0;if(total[k]>s.budgets[k])throw new Error(`${k} budget exceeded`)}if(next==="approval"&&(usage.approvals??0)<1)throw new Error("Explicit approval required");return{...s,stage:next,usage:total}}
export function groundedRecommendation(s:CopilotSession,text:string,evidence?:string,assumption?:string){if(!evidence&&!assumption)throw new Error("Recommendation must cite evidence or label an assumption");return{text:redactSecrets(text),grounding:evidence?{type:"evidence",value:evidence}:{type:"assumption",value:assumption},rankingGuarantee:false}}
