export interface SchemaEntity { id: string; types: string[]; properties: Record<string, unknown>; source: "json-ld" | "microdata" | "rdfa" }
export interface SchemaFinding { ruleId: string; severity: "low" | "medium" | "high"; entityId?: string; message: string; evidence: unknown; richResultGuarantee: false }
const supported = new Set(["Product","Article","NewsArticle","Organization","LocalBusiness","BreadcrumbList","Event","JobPosting","Recipe","VideoObject","SoftwareApplication","WebSite","ProfilePage","WebPage"]);
const googleRequired: Record<string,string[]> = { Product:["name","image"], Article:["headline","image","datePublished"], NewsArticle:["headline","image","datePublished"], LocalBusiness:["name","address"], Event:["name","startDate","location"], JobPosting:["title","datePosted","hiringOrganization"], Recipe:["name","image"], VideoObject:["name","thumbnailUrl","uploadDate"], SoftwareApplication:["name","offers"], BreadcrumbList:["itemListElement"] };
const asTypes = (value: unknown) => (Array.isArray(value) ? value : [value]).filter((item): item is string => typeof item === "string");
export function parseStructuredData(html: string, pageUrl = "https://invalid.local/") { const entities: SchemaEntity[] = []; const parseNode = (node: unknown, source: SchemaEntity["source"], index: number) => { if (!node || typeof node !== "object") return; const value = node as Record<string, unknown>; const graph = Array.isArray(value["@graph"]) ? value["@graph"] : [value]; graph.forEach((item, child) => { if (!item || typeof item !== "object") return; const props = item as Record<string, unknown>; const types = asTypes(props["@type"]); if (!types.length) return; entities.push({ id: typeof props["@id"] === "string" ? new URL(props["@id"], pageUrl).href : `${pageUrl}#${source}-${index}-${child}`, types, properties: props, source }); }); };
  [...html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].forEach((match, index) => { try { const value = JSON.parse(match[1]); (Array.isArray(value) ? value : [value]).forEach((node) => parseNode(node, "json-ld", index)); } catch { /* validation reports syntax separately */ } });
  [...html.matchAll(/<([a-z0-9-]+)\b[^>]*itemscope[^>]*itemtype=["']([^"']+)["'][^>]*>/gi)].forEach((match, index) => entities.push({ id: `${pageUrl}#microdata-${index}`, types: [match[2].split("/").pop()!], properties: {}, source: "microdata" }));
  [...html.matchAll(/<([a-z0-9-]+)\b[^>]*typeof=["']([^"']+)["'][^>]*>/gi)].forEach((match, index) => entities.push({ id: `${pageUrl}#rdfa-${index}`, types: match[2].split(/\s+/).map((type) => type.split(":").pop()!), properties: {}, source: "rdfa" })); return entities; }
export function validateStructuredData(html: string, pageUrl: string, visibleText: string, requiredTypes: string[] = []) { const entities = parseStructuredData(html, pageUrl); const findings: SchemaFinding[] = []; const add = (ruleId: string, severity: SchemaFinding["severity"], message: string, evidence: unknown, entityId?: string) => findings.push({ ruleId, severity, message, evidence, entityId, richResultGuarantee: false });
  const invalidJson = [...html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].filter((match) => { try { JSON.parse(match[1]); return false; } catch { return true; } }); if (invalidJson.length) add("schema-syntax", "high", `${invalidJson.length} JSON-LD block(s) are invalid`, { count: invalidJson.length });
  const ids = new Map<string, SchemaEntity[]>(); entities.forEach((entity) => ids.set(entity.id, [...(ids.get(entity.id) ?? []), entity])); ids.forEach((matches, id) => { if (matches.length > 1 && new Set(matches.flatMap((entity) => entity.types)).size > 1) add("schema-id-conflict", "high", "The same @id has conflicting types", matches.map((item) => item.types), id); });
  for (const entity of entities) { for (const type of entity.types) { if (!supported.has(type)) add("schema-unsupported-type", "low", `${type} is not covered by the current Google eligibility rules`, { type }, entity.id); for (const property of googleRequired[type] ?? []) if (entity.properties[property] === undefined) add("schema-required-property", "medium", `${type} is missing Google-required ${property}`, { type, property }, entity.id); } const name = entity.properties.name ?? entity.properties.headline; if (typeof name === "string" && !visibleText.toLowerCase().includes(name.toLowerCase())) add("schema-visible-content-mismatch", "high", "A marked-up claim is not present in visible content", { name }, entity.id); }
  for (const type of requiredTypes) if (!entities.some((entity) => entity.types.includes(type))) add("schema-required-type", "medium", `Required schema type ${type} is missing`, { type }); return { entities, findings, richResultEligibility: { possible: findings.every((item) => item.severity !== "high"), guaranteed: false as const } }; }
