import fs from "node:fs/promises";
import path from "node:path";
import { createHash, randomUUID } from "node:crypto";
export interface QualityPreset { name: string; maxCritical: number; maxHigh: number; failOnNew: boolean; minScores: Record<string, number> }
export interface RegisteredProject { id: string; name: string; root: string; retentionDays: number; presets: QualityPreset[]; branchPolicies: Record<string, { preset: string; protected: boolean }>; createdAt: string }
export interface RegistryData { version: 1; projects: RegisteredProject[] }
export class ProjectRegistry { constructor(private readonly file: string) {} private async read(): Promise<RegistryData> { try { const data = JSON.parse(await fs.readFile(this.file, "utf8")) as RegistryData; return data.version === 1 ? data : { version: 1, projects: [] }; } catch { return { version: 1, projects: [] }; } } private async write(data: RegistryData) { await fs.mkdir(path.dirname(this.file), { recursive: true }); const temp = `${this.file}.${process.pid}.tmp`; await fs.writeFile(temp, JSON.stringify(data, null, 2)); await fs.rename(temp, this.file); }
  async list() { return (await this.read()).projects; }
  async register(root: string, name = path.basename(root), retentionDays = 90) { const real = await fs.realpath(root); const pkg = await fs.access(path.join(real, "package.json")).then(() => true).catch(() => false); if (!pkg) throw new Error("Only JavaScript/TypeScript projects are supported"); const data = await this.read(); const existing = data.projects.find((p) => p.root.toLowerCase() === real.toLowerCase()); if (existing) return existing; const project: RegisteredProject = { id: randomUUID(), name, root: real, retentionDays: Math.max(1, Math.min(3650, retentionDays)), presets: [], branchPolicies: {}, createdAt: new Date().toISOString() }; data.projects.push(project); await this.write(data); return project; }
  async update(id: string, change: Partial<Pick<RegisteredProject, "name" | "retentionDays" | "presets" | "branchPolicies">>) { const data = await this.read(); const project = data.projects.find((p) => p.id === id); if (!project) throw new Error("Project not found"); Object.assign(project, change); await this.write(data); return project; }
  async remove(id: string) { const data = await this.read(); const next = data.projects.filter((p) => p.id !== id); if (next.length === data.projects.length) return false; data.projects = next; await this.write(data); return true; }
}
export function compareAuditRuns(before: { topIssues?: Array<{ id: string }>; summary?: { total: number }; qualityGate?: { passed: boolean } }, after: { topIssues?: Array<{ id: string }>; summary?: { total: number }; qualityGate?: { passed: boolean } }) { const oldIds = new Set((before.topIssues ?? []).map((i) => i.id)), newIds = new Set((after.topIssues ?? []).map((i) => i.id)); return { added: [...newIds].filter((id) => !oldIds.has(id)), resolved: [...oldIds].filter((id) => !newIds.has(id)), totalDelta: (after.summary?.total ?? newIds.size) - (before.summary?.total ?? oldIds.size), gateChanged: before.qualityGate?.passed !== after.qualityGate?.passed }; }
export function connectorPreview(type: "github" | "gitlab" | "jira" | "linear" | "slack", payload: { title: string; body: string; target: string }) { const redactedTarget = payload.target.replace(/([?&](?:token|key)=)[^&]+/gi, "$1<REDACTED>"); return { id: createHash("sha256").update(`${type}:${payload.title}:${payload.body}:${redactedTarget}`).digest("hex").slice(0, 16), type, target: redactedTarget, title: payload.title.slice(0, 200), body: payload.body.slice(0, 20_000), requiresApproval: true, sent: false }; }
