import crypto from "node:crypto";
export interface TeamSession { sessionId: string; actorId: string; tenantId: string; roles: string[]; csrfToken: string; issuedAt: number; expiresAt: number; }
export interface MembershipResolver { hasMembership(actorId: string, tenantId: string): Promise<boolean>; ownsResource(tenantId: string, resourceType: string, resourceId: string): Promise<boolean>; }
const encode = (value: unknown) => Buffer.from(JSON.stringify(value)).toString("base64url");
export class SessionSecurity {
  constructor(private readonly signingKey: Buffer, private readonly memberships: MembershipResolver, private readonly ttlMs = 8 * 60 * 60 * 1000) { if (signingKey.length < 32) throw new Error("Session signing key must be at least 256 bits"); }
  issue(actorId: string, tenantId: string, roles: string[]): { token: string; session: TeamSession } { const now = Date.now(); const session = { sessionId: crypto.randomUUID(), actorId, tenantId, roles: [...new Set(roles)], csrfToken: crypto.randomBytes(24).toString("base64url"), issuedAt: now, expiresAt: now + this.ttlMs }; const payload = encode(session); const signature = crypto.createHmac("sha256", this.signingKey).update(payload).digest("base64url"); return { token: `${payload}.${signature}`, session }; }
  async authenticate(token: string, expectedTenant: string): Promise<TeamSession> { const [payload, supplied, extra] = token.split("."); if (!payload || !supplied || extra) throw new Error("Invalid session"); const expected = crypto.createHmac("sha256", this.signingKey).update(payload).digest(); let actual: Buffer; try { actual = Buffer.from(supplied, "base64url"); } catch { throw new Error("Invalid session"); } if (actual.length !== expected.length || !crypto.timingSafeEqual(actual, expected)) throw new Error("Invalid session"); const session = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as TeamSession; if (session.expiresAt <= Date.now() || session.tenantId !== expectedTenant || !await this.memberships.hasMembership(session.actorId, session.tenantId)) throw new Error("Session expired or tenant membership denied"); return session; }
  requireCsrf(session: TeamSession, method: string, token: string | undefined, origin: string | undefined, allowedOrigin: string) { if (["GET","HEAD","OPTIONS"].includes(method)) return; if (!origin || origin !== allowedOrigin || !token) throw new Error("CSRF validation failed"); const expected = Buffer.from(session.csrfToken); const actual = Buffer.from(token); if (actual.length !== expected.length || !crypto.timingSafeEqual(actual, expected)) throw new Error("CSRF validation failed"); }
  async authorizeObject(session: TeamSession, resourceType: string, resourceId: string) { if (!await this.memberships.ownsResource(session.tenantId, resourceType, resourceId)) throw new Error("Object access denied"); }
}
