import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";
import { crawlToCsv, type CrawlProgress, type CrawlResult } from "../../../analyzers/seoCrawler";

type Status = "queued" | "running" | "completed" | "failed" | "cancelled";
interface CrawlJob { id: string; projectPath: string; url: string; status: Status; createdAt: string; progress?: CrawlProgress; resultPath?: string; error?: string; child?: ChildProcessWithoutNullStreams }
const bounded = (value: unknown, min: number, max: number, fallback: number) => typeof value === "number" && Number.isFinite(value) ? Math.max(min, Math.min(max, Math.floor(value))) : fallback;
const patterns = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string" && item.length <= 200).slice(0, 20).map((item) => new RegExp(item)) : undefined;
const send = (res: ServerResponse, status: number, value: unknown) => { res.writeHead(status, { "content-type": "application/json; charset=utf-8" }); res.end(JSON.stringify(value)); };
async function readBody(req: IncomingMessage) { const chunks: Buffer[] = []; for await (const chunk of req) chunks.push(Buffer.from(chunk)); return JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}") as Record<string, unknown>; }

export class LegacyCrawlRoutes {
  private readonly jobs = new Map<string, CrawlJob>();
  private readonly listeners = new Map<string, Set<ServerResponse>>();
  constructor(private readonly dependencies: { validateProject(input: unknown): Promise<string>; validateUrl(input: unknown): string | undefined; trusted(req: IncomingMessage): boolean }) {}
  private public(job: CrawlJob) { const { child: _child, ...safe } = job; return safe; }
  private emit(job: CrawlJob, event: string, data: unknown) { const value = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`; for (const response of this.listeners.get(job.id) ?? []) response.write(value); }
  private async start(job: CrawlJob, input: Record<string, unknown>) { job.status = "running"; const root = path.join(job.projectPath, "ai-auditor-report", "crawls"); await fs.mkdir(root, { recursive: true }); const options = { budget: { maxPages: bounded(input.maxPages, 1, 500, 100), maxDepth: bounded(input.maxDepth, 0, 10, 4), concurrency: bounded(input.concurrency, 1, 10, 3), delayMs: bounded(input.delayMs, 0, 10_000, 150), maxDurationMs: bounded(input.maxDurationMs, 1_000, 900_000, 120_000), maxResponseBytes: bounded(input.maxResponseBytes, 10_000, 10_000_000, 2_000_000) }, includeSubdomains: input.includeSubdomains === true, respectRobots: input.respectRobots !== false, include: patterns(input.include), exclude: patterns(input.exclude) }; const resumeId = typeof input.resumeId === "string" && /^[a-f0-9-]{36}$/.test(input.resumeId) ? input.resumeId : undefined; const payload = Buffer.from(JSON.stringify({ url: job.url, options, resumeFile: resumeId ? path.join(root, `${resumeId}.json`) : undefined })).toString("base64url"); const child = spawn(process.execPath, ["--max-old-space-size=256", path.resolve(__dirname, "../../crawlWorker.js"), payload], { cwd: job.projectPath, shell: false, windowsHide: true }); job.child = child; let buffered = ""; child.stdout.on("data", (chunk: Buffer) => { buffered += chunk.toString(); const lines = buffered.split(/\r?\n/); buffered = lines.pop() ?? ""; for (const line of lines) try { const message = JSON.parse(line) as { type: string; progress?: CrawlProgress; result?: CrawlResult }; if (message.type === "progress" && message.progress) { job.progress = message.progress; this.emit(job, "progress", message.progress); } if (message.type === "result" && message.result) { job.resultPath = path.join(root, `${job.id}.json`); void fs.writeFile(job.resultPath, JSON.stringify(message.result, null, 2)); } } catch {} }); child.stderr.on("data", (chunk: Buffer) => { job.error = `${job.error ?? ""}${chunk.toString()}`.slice(-4000); }); child.on("close", () => { job.status = job.status === "cancelled" ? "cancelled" : job.resultPath ? "completed" : "failed"; delete job.child; this.emit(job, "status", this.public(job)); for (const response of this.listeners.get(job.id) ?? []) response.end(); this.listeners.delete(job.id); }); this.emit(job, "status", this.public(job)); }
  async handle(req: IncomingMessage, res: ServerResponse, url: URL): Promise<boolean> { if (!url.pathname.startsWith("/api/crawls")) return false; if (req.method === "GET" && url.pathname === "/api/crawls") { send(res, 200, [...this.jobs.values()].map((job) => this.public(job)).reverse()); return true; } if (req.method === "POST" && url.pathname === "/api/crawls") { if (!this.dependencies.trusted(req)) { send(res, 403, { error: "Cross-site request rejected" }); return true; } const input = await readBody(req); const projectPath = await this.dependencies.validateProject(input.projectPath); const crawlUrl = this.dependencies.validateUrl(input.url); if (!crawlUrl) throw new Error("Crawl URL is required"); const job: CrawlJob = { id: randomUUID(), projectPath, url: crawlUrl, status: "queued", createdAt: new Date().toISOString() }; this.jobs.set(job.id, job); send(res, 202, this.public(job)); setImmediate(() => void this.start(job, input)); return true; } const events = url.pathname.match(/^\/api\/crawls\/([^/]+)\/events$/); if (req.method === "GET" && events) { const job = this.jobs.get(events[1]); if (!job) { send(res, 404, { error: "Crawl not found" }); return true; } res.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" }); res.write(`event: status\ndata: ${JSON.stringify(this.public(job))}\n\n`); if (job.progress) res.write(`event: progress\ndata: ${JSON.stringify(job.progress)}\n\n`); if (["completed", "failed", "cancelled"].includes(job.status)) { res.end(); return true; } const set = this.listeners.get(job.id) ?? new Set<ServerResponse>(); set.add(res); this.listeners.set(job.id, set); req.on("close", () => set.delete(res)); return true; } const resultMatch = url.pathname.match(/^\/api\/crawls\/([^/]+)\/result$/); if (req.method === "GET" && resultMatch) { const job = this.jobs.get(resultMatch[1]); if (!job?.resultPath) { send(res, 404, { error: "Crawl result not available" }); return true; } const result = JSON.parse(await fs.readFile(job.resultPath, "utf8")) as CrawlResult; if (url.searchParams.get("format") === "csv") { res.writeHead(200, { "content-type": "text/csv; charset=utf-8", "content-disposition": "attachment; filename=seo-crawl.csv" }); res.end(crawlToCsv(result)); return true; } send(res, 200, result); return true; } const cancel = url.pathname.match(/^\/api\/crawls\/([^/]+)\/cancel$/); if (req.method === "POST" && cancel) { const job = this.jobs.get(cancel[1]); if (!job?.child || job.status !== "running") { send(res, 409, { error: "Crawl is not running" }); return true; } job.status = "cancelled"; job.child.kill(); send(res, 202, this.public(job)); return true; } return false; }
}
